/* Content — Pure Mathematics rooms P6–P10. */
const ROOMS = [];

ROOMS.push({
 id:'P6', name:'Exponentials and logarithms', paper:'1/2',
 upLearn:'Exponentials and logarithms',
 pearson:'Pure Year 1: Ch 14 Exponentials and logarithms',
 concept:'A logarithm answers the question "what power?". Once that clicks, the laws of logs are just the laws of indices read backwards. The number e matters because y = eˣ is the one exponential whose gradient equals its own value, which is why it runs through all of calculus. Exam questions come in three shapes: solve an equation with the unknown in the power (take logs), model growth or decay (N = Ae^{kt}, find the constants), and linearise a relationship (y = axⁿ becomes log y = log a + n log x, a straight line). The commonest lost mark: forgetting that log of a negative number does not exist, so a solution must be checked against the original equation.',
 formulae:['log_a x = y ⟺ a^y = x',
  'log(xy) = log x + log y; log(x/y) = log x − log y; log(xᵏ) = k log x',
  'log_a a = 1; log_a 1 = 0; a^(log_a x) = x',
  'eˣ and ln x are inverses: ln(eˣ) = x, e^(ln x) = x',
  'Solving aˣ = b: x = log b / log a',
  'y = axⁿ ⟹ log y = n log x + log a (gradient n, intercept log a)'],
 videos:[{ch:'TLMaths',q:'TLMaths laws of logarithms solving exponential equations'},
  {ch:'ExamSolutions',q:'ExamSolutions exponential modelling growth decay A level'}],
 examples:[
  {title:'Solve 5ˣ = 2ˣ⁺¹, giving x to 3 significant figures',
   steps:['Take natural logs of both sides: x ln 5 = (x + 1) ln 2.',
    'Expand the right: x ln 5 = x ln 2 + ln 2.',
    'Collect x terms: x(ln 5 − ln 2) = ln 2.',
    'So x = ln 2 / (ln 5 − ln 2) = ln 2 / ln 2.5.',
    'x ≈ 0.6931 / 0.9163 = 0.756 (3 s.f.).']},
  {title:'Sketch y = eˣ − 2, stating where it crosses the axes and its asymptote',
   steps:['As x → −∞, eˣ → 0, so y → −2. The horizontal asymptote is y = −2.',
    'At x = 0, y = 1 − 2 = −1. The curve crosses the y-axis at (0, −1).',
    'Where y = 0: eˣ = 2, so x = ln 2. Crosses the x-axis at (ln 2, 0).',
    'Shape: the standard eˣ curve shifted down 2 units, increasing throughout.']}],
 questions:[
  {q:'Solve 2ˣ = 20, giving x to 3 significant figures.', a:'x = 4.32', sol:'x = log 20 / log 2 = 1.3010/0.3010 = 4.32.', m:2, d:1,
   hints:['Take logs of both sides.','x log 2 = log 20.','Divide.']},
  {q:'Evaluate log₃ 81 and log₂(1/8).', a:'4 and −3', sol:'3⁴ = 81, so 4. 2⁻³ = 1/8, so −3.', m:2, d:1,
   hints:['Ask "3 to what power gives 81?"','1/8 = 2⁻³.','A log of a number less than 1 is negative.']},
  {q:'Solve log₂ x + log₂(x − 2) = 3.', a:'x = 4', sol:'log₂(x(x − 2)) = 3, so x² − 2x = 8, (x − 4)(x + 2) = 0. x = −2 is rejected because log₂(−2) is undefined. x = 4.', m:4, d:2,
   hints:['Combine using log a + log b = log(ab).','Then rewrite log₂(…) = 3 as … = 2³.','Check both roots in the original equation — one of them fails.']},
  {q:'Write 2 ln x − ln 4 as a single logarithm.', a:'ln(x²/4)', sol:'2 ln x = ln x²; ln x² − ln 4 = ln(x²/4).', m:2, d:1,
   hints:['Move the 2 inside as a power.','Then use ln a − ln b = ln(a/b).','ln(x²/4).']},
  {q:'Solve e²ˣ − 3eˣ + 2 = 0.', a:'x = 0 or x = ln 2', sol:'Let u = eˣ: u² − 3u + 2 = 0, (u − 1)(u − 2) = 0. eˣ = 1 gives x = 0; eˣ = 2 gives x = ln 2.', m:4, d:2,
   hints:['This is a quadratic in disguise.','Let u = eˣ, so e²ˣ = u².','Solve for u, then take ln.']},
  {q:'A population is modelled by N = 50e^{0.2t}. Find N when t = 10, and the time taken for the population to double.', a:'N ≈ 369; doubling time ≈ 3.47', sol:'N = 50e² = 369.5. Doubling: e^{0.2t} = 2, 0.2t = ln 2, t = 3.466.', m:4, d:2,
   hints:['Substitute t = 10 directly for the first part.','For doubling, you want e^{0.2t} = 2 — the 50 cancels.','Take ln of both sides.']},
  {q:'A relationship y = axⁿ is investigated. A plot of log₁₀ y against log₁₀ x is a straight line with equation log₁₀ y = 0.3 + 2 log₁₀ x. Find a and n.', a:'n = 2, a = 10^0.3 ≈ 2.00', sol:'log y = log a + n log x. Comparing: n = 2 and log a = 0.3, so a = 10^0.3 = 1.995.', m:3, d:3,
   hints:['Take logs of y = axⁿ: log y = log a + n log x.','The gradient of the line is n.','The intercept is log a, so a = 10^(intercept).']},
  {q:'Solve 3²ˣ⁺¹ = 10, giving x to 3 significant figures.', a:'x = 0.548', sol:'(2x + 1) log 3 = log 10 = 1. 2x + 1 = 1/0.4771 = 2.096. x = 0.548.', m:3, d:2,
   hints:['Take logs: (2x + 1) log 3 = log 10.','Divide by log 3 first.','Then subtract 1 and halve.']}],
 exit:[{q:'Evaluate log₅ 125.',a:'3'},
  {q:'State the value of e⁰.',a:'1'},
  {q:'Simplify ln(e³).',a:'3'}]
});

ROOMS.push({
 id:'P7', name:'Differentiation', paper:'1/2',
 upLearn:'Differentiation (Pure Year 1 and Year 2 lessons)',
 pearson:'Pure Year 1: Ch 12 Differentiation. Pure Year 2: Ch 9 Differentiation',
 concept:'Differentiation measures rate of change: the gradient of a curve at a point. Year 1 gives you the power rule and its uses — tangents, normals, stationary points, increasing and decreasing functions. Year 2 gives you the rest of the toolkit: chain, product and quotient rules, the derivatives of trig, exponential and log functions, implicit and parametric differentiation, and the second derivative for convexity and points of inflection. Watch the 3Blue1Brown Essence of Calculus series before starting this room; twenty minutes on what a derivative actually is saves hours later. Examiners love connected rates of change — a chain rule in disguise — and questions that ask you to justify the nature of a stationary point.',
 formulae:['d/dx (xⁿ) = nxⁿ⁻¹; d/dx (eᵏˣ) = keᵏˣ; d/dx (ln x) = 1/x',
  'd/dx (sin x) = cos x; d/dx (cos x) = −sin x; d/dx (tan x) = sec²x',
  'Chain: dy/dx = dy/du × du/dx',
  'Product: (uv)′ = u′v + uv′; Quotient: (u/v)′ = (u′v − uv′)/v²',
  'Parametric: dy/dx = (dy/dt)/(dx/dt)',
  'First principles: f′(x) = lim_{h→0} (f(x + h) − f(x))/h',
  'Stationary point: f′ = 0. f″ > 0 minimum, f″ < 0 maximum. Inflection: f″ changes sign'],
 videos:[{ch:'3Blue1Brown',q:'3Blue1Brown Essence of calculus chapter 2 paradox of the derivative'},
  {ch:'TLMaths',q:'TLMaths implicit differentiation A level'},
  {ch:'ExamSolutions',q:'ExamSolutions connected rates of change chain rule'}],
 examples:[
  {title:'Differentiate f(x) = x² from first principles',
   steps:['f(x + h) = (x + h)² = x² + 2xh + h².',
    'f(x + h) − f(x) = 2xh + h².',
    'Divide by h: (2xh + h²)/h = 2x + h.',
    'Take the limit as h → 0: 2x + h → 2x.',
    'So f′(x) = 2x.']},
  {title:'Find where y = x³ − 6x² is concave, and locate its point of inflection',
   steps:['dy/dx = 3x² − 12x.',
    'd²y/dx² = 6x − 12.',
    'Concave where d²y/dx² < 0: 6x − 12 < 0, so x < 2.',
    'Point of inflection where d²y/dx² = 0 and changes sign: x = 2.',
    'At x = 2, y = 8 − 24 = −16. Inflection at (2, −16).']}],
 questions:[
  {q:'Differentiate y = 3x⁴ − 2x² + 5.', a:'12x³ − 4x', sol:'Term by term with the power rule.', m:2, d:1,
   hints:['Bring the power down and reduce it by 1, for each term.','The constant 5 differentiates to 0.','3 × 4 = 12 for the first coefficient.']},
  {q:'Differentiate y = (2x + 1)⁵.', a:'10(2x + 1)⁴', sol:'Chain rule: 5(2x + 1)⁴ × 2.', m:2, d:1,
   hints:['This is a function of a function — chain rule.','Differentiate the outside: 5(…)⁴.','Multiply by the derivative of the inside, which is 2.']},
  {q:'Differentiate y = x²e³ˣ.', a:'xe³ˣ(2 + 3x)', sol:'Product rule: 2x·e³ˣ + x²·3e³ˣ = e³ˣ(2x + 3x²) = xe³ˣ(2 + 3x).', m:3, d:2,
   hints:['Product rule: u = x², v = e³ˣ.','u′ = 2x, v′ = 3e³ˣ.','Factorise the answer — examiners expect it.']},
  {q:'Differentiate y = sin x / x.', a:'(x cos x − sin x)/x²', sol:'Quotient rule: (cos x · x − sin x · 1)/x².', m:3, d:2,
   hints:['Quotient rule with u = sin x, v = x.','(u′v − uv′)/v².','Keep the order in the numerator right — it matters.']},
  {q:'Find the stationary points of y = x³ − 3x² − 9x + 5 and determine their nature.', a:'(−1, 10) maximum; (3, −22) minimum', sol:'y′ = 3x² − 6x − 9 = 3(x − 3)(x + 1). y″ = 6x − 6. At x = −1: y″ < 0, maximum, y = 10. At x = 3: y″ > 0, minimum, y = −22.', m:5, d:2,
   hints:['Set dy/dx = 0 and solve.','Factorise 3x² − 6x − 9 by taking out 3 first.','Use the second derivative to decide max or min at each point.']},
  {q:'The curve x² + xy + y² = 7 passes through (1, 2). Find dy/dx at that point.', a:'−4/5', sol:'2x + y + x(dy/dx) + 2y(dy/dx) = 0. At (1, 2): 2 + 2 + (1 + 4)(dy/dx) = 0, so dy/dx = −4/5.', m:4, d:3,
   hints:['Differentiate every term with respect to x; y terms need dy/dx.','xy needs the product rule: y + x(dy/dx).','Substitute the point in before rearranging — it\'s less work.']},
  {q:'The radius of a sphere is increasing at 0.1 cm s⁻¹. Find the rate of increase of its volume when r = 2 cm. (V = 4/3 πr³)', a:'1.6π cm³ s⁻¹', sol:'dV/dt = dV/dr × dr/dt = 4πr² × 0.1. At r = 2: 4π·4·0.1 = 1.6π.', m:3, d:3,
   hints:['This is a chain rule: dV/dt = dV/dr × dr/dt.','dV/dr = 4πr².','Substitute r = 2 and dr/dt = 0.1.']},
  {q:'A curve has parametric equations x = t², y = t³. Find dy/dx in terms of t.', a:'3t/2', sol:'dx/dt = 2t, dy/dt = 3t². dy/dx = 3t²/(2t) = 3t/2.', m:2, d:2,
   hints:['Differentiate x and y with respect to t.','dy/dx = (dy/dt)/(dx/dt).','Cancel a factor of t.']}],
 exit:[{q:'Differentiate x⁻².',a:'−2x⁻³'},
  {q:'Differentiate ln x.',a:'1/x'},
  {q:'Find the gradient of y = x² at x = 3.',a:'6'}]
});

ROOMS.push({
 id:'P8', name:'Integration', paper:'1/2',
 upLearn:'Integration (Pure Year 1 and Year 2 lessons)',
 pearson:'Pure Year 1: Ch 13 Integration. Pure Year 2: Ch 11 Integration',
 concept:'Integration is differentiation reversed, and then it is a great deal more. Year 1: reverse the power rule, evaluate definite integrals, find areas under and between curves. Year 2: the standard integrals of trig and exponential functions, then the three big techniques — substitution, integration by parts, and partial fractions — and finally separable differential equations, which is where integration starts describing the real world. The skill that separates grades here is recognising which technique a given integral wants; that is a METHOD-CHOICE skill and it only comes from interleaved practice. Always check an indefinite integral by differentiating it back.',
 formulae:['∫ xⁿ dx = xⁿ⁺¹/(n + 1) + c (n ≠ −1); ∫ 1/x dx = ln|x| + c',
  '∫ eᵏˣ dx = eᵏˣ/k + c; ∫ sin x dx = −cos x + c; ∫ cos x dx = sin x + c',
  '∫ f′(x)/f(x) dx = ln|f(x)| + c',
  'By parts: ∫ u (dv/dx) dx = uv − ∫ v (du/dx) dx',
  'Trapezium rule: ∫ y dx ≈ h/2 [y₀ + 2(y₁ + … + yₙ₋₁) + yₙ], h = (b − a)/n',
  'Separable DE: dy/dx = f(x)g(y) ⟹ ∫ 1/g(y) dy = ∫ f(x) dx'],
 videos:[{ch:'3Blue1Brown',q:'3Blue1Brown Essence of calculus integration fundamental theorem'},
  {ch:'TLMaths',q:'TLMaths integration by parts substitution A level'},
  {ch:'ExamSolutions',q:'ExamSolutions differential equations separating variables'}],
 examples:[
  {title:'Evaluate ∫₀^{π/2} sin²x dx',
   steps:['Use the double-angle identity: sin²x = (1 − cos 2x)/2.',
    'So the integral is ∫₀^{π/2} (1/2 − (cos 2x)/2) dx.',
    'Integrate: [x/2 − (sin 2x)/4] from 0 to π/2.',
    'At π/2: π/4 − sin(π)/4 = π/4. At 0: 0.',
    'Result: π/4.']},
  {title:'Find ∫ 2x(x² + 1)³ dx using the substitution u = x² + 1',
   steps:['du/dx = 2x, so du = 2x dx.',
    'The integral becomes ∫ u³ du.',
    'Integrate: u⁴/4 + c.',
    'Substitute back: (x² + 1)⁴/4 + c.',
    'Check by differentiating: 4(x² + 1)³ · 2x / 4 = 2x(x² + 1)³. ✓']}],
 questions:[
  {q:'Find ∫ (6x² − 4x + 1) dx.', a:'2x³ − 2x² + x + c', sol:'Term by term, and do not forget + c.', m:2, d:1,
   hints:['Raise each power by 1 and divide by the new power.','6x²/3 = 2x³.','Indefinite integrals always need + c.']},
  {q:'Evaluate ∫₁⁴ √x dx.', a:'14/3', sol:'∫ x^{1/2} dx = (2/3)x^{3/2}. [(2/3)·8] − [(2/3)·1] = 16/3 − 2/3 = 14/3.', m:3, d:1,
   hints:['Write √x as x^{1/2}.','x^{3/2} at x = 4 is 8.','Subtract the value at the lower limit.']},
  {q:'Find ∫ x e^{x²} dx.', a:'½e^{x²} + c', sol:'The derivative of x² is 2x, so this is ½ ∫ 2x e^{x²} dx = ½e^{x²} + c.', m:2, d:2,
   hints:['Notice that x is almost the derivative of x².','Substitute u = x², du = 2x dx.','You need a factor of ½ to balance.']},
  {q:'Find ∫ x cos x dx.', a:'x sin x + cos x + c', sol:'By parts with u = x, dv/dx = cos x: x sin x − ∫ sin x dx = x sin x + cos x + c.', m:3, d:2,
   hints:['A product of a polynomial and a trig function suggests by parts.','Let u = x (it gets simpler when differentiated).','∫ sin x dx = −cos x, and there is a minus sign in the formula.']},
  {q:'Find ∫ 1/(x² − 1) dx.', a:'½ ln|(x − 1)/(x + 1)| + c', sol:'1/((x − 1)(x + 1)) = ½[1/(x − 1) − 1/(x + 1)]. Integrate to ½[ln|x − 1| − ln|x + 1|].', m:4, d:3,
   hints:['Factorise the denominator.','Split into partial fractions.','Each piece integrates to a log.']},
  {q:'Find the area enclosed between y = x² and y = x + 2.', a:'9/2', sol:'Intersect: x² = x + 2, x = −1, 2. Area = ∫₋₁² (x + 2 − x²) dx = [x²/2 + 2x − x³/3]₋₁² = (2 + 4 − 8/3) − (1/2 − 2 + 1/3) = 10/3 + 7/6 = 9/2.', m:5, d:3,
   hints:['Find where the curves meet first.','Integrate (top curve − bottom curve) between those limits.','The line is above the parabola between the intersections.']},
  {q:'Solve dy/dx = xy given that y = 2 when x = 0.', a:'y = 2e^{x²/2}', sol:'∫ 1/y dy = ∫ x dx, ln y = x²/2 + c. y(0) = 2 gives c = ln 2. y = 2e^{x²/2}.', m:4, d:3,
   hints:['Separate the variables: dy/y = x dx.','Integrate both sides — remember + c on one side.','Use the initial condition to find c, then rearrange for y.']},
  {q:'Find ∫ tan x dx.', a:'ln|sec x| + c (or −ln|cos x| + c)', sol:'tan x = sin x / cos x = −(−sin x)/cos x, so the integral is −ln|cos x| + c.', m:2, d:2,
   hints:['Write tan x as sin x / cos x.','The numerator is (minus) the derivative of the denominator.','∫ f′/f = ln|f|.']}],
 exit:[{q:'Find ∫ x³ dx.',a:'x⁴/4 + c'},
  {q:'Evaluate ∫₀¹ 2x dx.',a:'1'},
  {q:'Find ∫ e²ˣ dx.',a:'½e²ˣ + c'}]
});

ROOMS.push({
 id:'P9', name:'Numerical methods', paper:'1/2',
 upLearn:'Numerical methods: iteration, Newton–Raphson, trapezium rule',
 pearson:'Pure Year 2: Ch 10 Numerical methods (trapezium rule also in Ch 11 Integration)',
 concept:'When an equation cannot be solved exactly, you locate a root (a change of sign in a continuous function) and then home in on it. Two ways: rearrange to x = g(x) and iterate, or use Newton–Raphson, which follows tangents to the root and converges fast unless it starts near a turning point. The trapezium rule does the same job for integrals you cannot do exactly. This is a short room but the marks demand precise language — "there is a change of sign and f is continuous, so a root lies between…" earns the mark; "it changes sign so there\'s a root" may not. Calculator fluency matters here more than anywhere else in pure.',
 formulae:['Change of sign: if f is continuous on [a, b] and f(a), f(b) have opposite signs, a root lies in (a, b)',
  'Iteration: xₙ₊₁ = g(xₙ), converges near root α if |g′(α)| < 1',
  'Newton–Raphson: xₙ₊₁ = xₙ − f(xₙ)/f′(xₙ)',
  'Trapezium rule: h = (b − a)/n; ∫ ≈ h/2 [y₀ + 2(y₁ + … + yₙ₋₁) + yₙ]',
  'A convex curve gives an overestimate with the trapezium rule; concave gives an underestimate'],
 videos:[{ch:'TLMaths',q:'TLMaths Newton Raphson method A level'},
  {ch:'ExamSolutions',q:'ExamSolutions iteration staircase cobweb diagrams'}],
 examples:[
  {title:'Use Newton–Raphson twice on x² − 3 = 0 starting from x₀ = 2',
   steps:['f(x) = x² − 3, so f′(x) = 2x.',
    'x₁ = 2 − (4 − 3)/(4) = 2 − 0.25 = 1.75.',
    'f(1.75) = 3.0625 − 3 = 0.0625; f′(1.75) = 3.5.',
    'x₂ = 1.75 − 0.0625/3.5 = 1.75 − 0.017857 = 1.7321.',
    'Compare with √3 = 1.73205: two steps already give five correct figures.']},
  {title:'Trapezium rule for ∫₀² x² dx with 2 strips, then 4 strips',
   steps:['With 2 strips: h = 1, y-values 0, 1, 4. Estimate = ½[0 + 2(1) + 4] = 3.',
    'With 4 strips: h = 0.5, y-values 0, 0.25, 1, 2.25, 4.',
    'Estimate = 0.25[0 + 2(0.25 + 1 + 2.25) + 4] = 0.25[7 + 4] = 2.75.',
    'The exact value is 8/3 = 2.667. Both estimates are too large because the curve is convex.',
    'More strips → closer to the true value.']}],
 questions:[
  {q:'Show that f(x) = x³ − 2x − 5 has a root between x = 2 and x = 3.', a:'f(2) = −1 < 0, f(3) = 16 > 0; sign change and f continuous', sol:'f(2) = 8 − 4 − 5 = −1. f(3) = 27 − 6 − 5 = 16. There is a change of sign and f is continuous, so a root lies in (2, 3).', m:2, d:1,
   hints:['Evaluate f at both ends.','State the signs explicitly.','The word "continuous" is part of the answer.']},
  {q:'Using xₙ₊₁ = √(2xₙ + 5) with x₀ = 2, find x₁, x₂ and x₃ to 4 decimal places.', a:'3, 3.3166, 3.4108', sol:'x₁ = √9 = 3; x₂ = √11 = 3.3166; x₃ = √(11.6332) = 3.4108.', m:3, d:2,
   hints:['Substitute x₀ = 2 into the right-hand side.','Use the previous answer each time — keep full calculator accuracy.','Round only when writing each value down.']},
  {q:'Apply one iteration of Newton–Raphson to f(x) = x³ − 2x − 5 starting at x₀ = 2.', a:'x₁ = 2.1', sol:'f′(x) = 3x² − 2. x₁ = 2 − (−1)/(12 − 2) = 2 + 0.1 = 2.1.', m:3, d:2,
   hints:['Find f′(x) first.','x₁ = x₀ − f(x₀)/f′(x₀).','f(2) = −1 and f′(2) = 10.']},
  {q:'Use the trapezium rule with 4 strips to estimate ∫₀² x² dx.', a:'2.75', sol:'h = 0.5. y = 0, 0.25, 1, 2.25, 4. Estimate = 0.25[(0 + 4) + 2(0.25 + 1 + 2.25)] = 0.25 × 11 = 2.75.', m:4, d:2,
   hints:['h = (2 − 0)/4 = 0.5, so you need 5 y-values.','The formula doubles the inner values but not the ends.','Multiply the bracket by h/2.']},
  {q:'Explain why Newton–Raphson fails if x₀ is chosen at a stationary point of f.', a:'f′(x₀) = 0, so the formula divides by zero; the tangent is horizontal and never meets the x-axis', sol:'The method uses the tangent at x₀. At a stationary point the tangent is horizontal, so it does not cross the x-axis, and f′(x₀) = 0 makes the formula undefined.', m:2, d:1,
   hints:['Look at the formula — what is in the denominator?','What is f′ at a stationary point?','Think about the tangent line geometrically.']},
  {q:'Rearrange x³ − 2x − 5 = 0 into the form x = g(x) in two different ways.', a:'x = (2x + 5)^{1/3} and x = (x³ − 5)/2', sol:'From x³ = 2x + 5: x = ∛(2x + 5). From 2x = x³ − 5: x = (x³ − 5)/2.', m:2, d:1,
   hints:['Isolate the x³ term for one version.','Isolate the 2x term for another.','Each gives a different iterative formula.']},
  {q:'Is the estimate 2.75 for ∫₀² x² dx an overestimate or an underestimate? Justify your answer.', a:'Overestimate; y = x² is convex, so the trapezia lie above the curve', sol:'The curve is convex (d²y/dx² = 2 > 0), so each chord lies above the curve and the trapezia contain extra area.', m:2, d:2,
   hints:['Sketch the curve and one trapezium.','Is the chord above or below the curve?','Convex curves give overestimates.']},
  {q:'For g(x) = (2x + 5)^{1/3}, show that the iteration xₙ₊₁ = g(xₙ) converges to the root near 2.09.', a:'g′(2.09) ≈ 0.15, and |g′| < 1 so it converges', sol:'g′(x) = (2/3)(2x + 5)^{−2/3}. At x = 2.09: (2/3)(9.18)^{−2/3} ≈ (2/3)(0.228) ≈ 0.15. Since |g′(α)| < 1, the iteration converges.', m:3, d:3,
   hints:['Differentiate g.','Evaluate |g′| near the root.','The condition for convergence is |g′(α)| < 1.']}],
 exit:[{q:'What does a change of sign of a continuous function between a and b tell you?',a:'A root lies between a and b'},
  {q:'For the trapezium rule with n strips on [a, b], what is h?',a:'h = (b − a)/n'},
  {q:'State the Newton–Raphson formula.',a:'xₙ₊₁ = xₙ − f(xₙ)/f′(xₙ)'}]
});

ROOMS.push({
 id:'P10', name:'Vectors', paper:'1/2',
 upLearn:'Vectors in 2D and 3D',
 pearson:'Pure Year 1: Ch 11 Vectors. Pure Year 2: Ch 12 Vectors',
 concept:'A vector has magnitude and direction; a scalar has only size. In this course vectors are column vectors or i, j, k form, in two dimensions in Year 1 and three in Year 2. You add them tip to tail, scale them, find their length with Pythagoras, and use position vectors to prove geometric facts — that points are collinear, that a shape is a parallelogram, where a line is divided in a given ratio. Note what is not here: there is no scalar (dot) product in A level Mathematics; that belongs to Further Maths. Use GeoGebra\'s 3D view when you first meet three-dimensional vectors — it makes the geometry obvious in a way paper cannot.',
 formulae:['|ai + bj| = √(a² + b²); |ai + bj + ck| = √(a² + b² + c²)',
  'Vector from A to B: AB = b − a (position vectors)',
  'Unit vector in the direction of v: v/|v|',
  'Parallel vectors: one is a scalar multiple of the other',
  'Collinear points: AB is a scalar multiple of BC',
  'Point P dividing AB in ratio m : n: OP = a + m/(m + n) (b − a)'],
 videos:[{ch:'TLMaths',q:'TLMaths vectors 3D geometric problems A level'},
  {ch:'ExamSolutions',q:'ExamSolutions position vectors ratio problems'}],
 examples:[
  {title:'Show that A(1, 1, 1), B(2, 3, 5) and C(4, 7, 13) are collinear',
   steps:['AB = b − a = (2 − 1, 3 − 1, 5 − 1) = (1, 2, 4).',
    'BC = c − b = (4 − 2, 7 − 3, 13 − 5) = (2, 4, 8).',
    'BC = 2 × AB, so AB and BC are parallel.',
    'They share the point B, so A, B and C lie on one straight line.']},
  {title:'Find the unit vector in the direction of 6i − 8j, and its magnitude',
   steps:['Magnitude: √(6² + (−8)²) = √(36 + 64) = √100 = 10.',
    'Divide the vector by its magnitude: (6i − 8j)/10.',
    'Unit vector: 0.6i − 0.8j.',
    'Check: √(0.36 + 0.64) = 1. ✓']}],
 questions:[
  {q:'a = 3i − 2j and b = i + 4j. Find a + b and |a|.', a:'a + b = 4i + 2j; |a| = √13', sol:'Add components: (3 + 1)i + (−2 + 4)j. |a| = √(9 + 4) = √13.', m:2, d:1,
   hints:['Add the i parts together and the j parts together.','Magnitude uses Pythagoras on the components.','√13 is exact — leave it as a surd.']},
  {q:'Find the unit vector in the direction of 6i − 8j.', a:'0.6i − 0.8j', sol:'|6i − 8j| = 10, so divide by 10.', m:2, d:1,
   hints:['Find the magnitude first.','√(36 + 64) = 10.','Divide each component by 10.']},
  {q:'A(1, 2, 3) and B(4, −2, 15). Find the vector AB and the distance AB.', a:'AB = (3, −4, 12); |AB| = 13', sol:'b − a = (3, −4, 12). √(9 + 16 + 144) = √169 = 13.', m:3, d:2,
   hints:['AB = b − a, component by component.','Three components now — Pythagoras in 3D.','9 + 16 + 144 = 169.']},
  {q:'Find λ such that 2i + λj is parallel to 6i − 9j.', a:'λ = −3', sol:'6i − 9j = 3(2i − 3j), so λ = −3.', m:2, d:1,
   hints:['Parallel means one is a multiple of the other.','6 = 3 × 2, so the multiplier is 3.','Then λ × 3 = −9.']},
  {q:'Points A and B have position vectors a = (2, 1, 0) and b = (4, 5, 2). Find the position vector of the midpoint M of AB.', a:'(3, 3, 1)', sol:'m = (a + b)/2 = (6, 6, 2)/2 = (3, 3, 1).', m:2, d:1,
   hints:['The midpoint is halfway along.','m = ½(a + b).','Average each component.']},
  {q:'Show that A(1, 1, 1), B(2, 3, 5) and C(4, 7, 13) are collinear.', a:'AB = (1, 2, 4), BC = (2, 4, 8) = 2AB', sol:'BC is a multiple of AB and they share B, so the points are collinear.', m:3, d:2,
   hints:['Find AB and BC.','Are they parallel — is one a multiple of the other?','Parallel and sharing a point means collinear.']},
  {q:'Find the distance between A(2, −1, 3) and B(5, 3, 3).', a:'5', sol:'AB = (3, 4, 0). √(9 + 16 + 0) = 5.', m:2, d:1,
   hints:['Find the vector AB first.','The k component is 0.','√(9 + 16).']},
  {q:'OA = a and OB = b. The point P lies on AB such that AP : PB = 1 : 2. Find OP in terms of a and b.', a:'OP = (2a + b)/3', sol:'AP = ⅓AB = ⅓(b − a). OP = a + ⅓(b − a) = (2a + b)/3.', m:3, d:3,
   hints:['P is one third of the way from A to B.','AP = ⅓(b − a).','OP = OA + AP.']}],
 exit:[{q:'Find |5i + 12j|.',a:'13'},
  {q:'Find the vector from (1, 2) to (4, 6).',a:'3i + 4j'},
  {q:'Find the magnitude of (1, 2, 2).',a:'3'}]
});

module.exports = { ROOMS };
