/* Content — Pure Mathematics rooms P1–P5. Original material, spec-aligned. */
const ROOMS = [];

ROOMS.push({
 id:'P2', name:'Algebra and functions', paper:'1/2',
 upLearn:'Algebra & functions (Pure Year 1 and Year 2 lessons)',
 pearson:'Pure Year 1: Ch 1 Algebraic expressions, Ch 2 Quadratics, Ch 3 Equations and inequalities, Ch 4 Graphs and transformations, Ch 7 Algebraic methods. Pure Year 2: Ch 1 Algebraic methods, Ch 2 Functions and graphs',
 concept:'Everything in A level maths stands on this room. Indices and surds are the vocabulary; quadratics are the first structure you learn to read completely (roots, vertex, discriminant); inequalities, polynomials and graph transformations turn that reading into a toolkit. In Year 2 the room grows to include functions as objects — composite, inverse, modulus — and partial fractions, which integration will need later. The single habit that matters most here: never do a manipulation in your head that you could write down. That is where marks go missing.',
 formulae:['Laws of indices: a^m × a^n = a^(m+n), (a^m)^n = a^(mn), a^(-n) = 1/a^n, a^(1/n) = ⁿ√a',
  'Quadratic formula: x = (−b ± √(b² − 4ac)) / 2a',
  'Discriminant b² − 4ac: > 0 two real roots, = 0 one repeated root, < 0 no real roots',
  'Completed square: x² + bx + c = (x + b/2)² − b²/4 + c',
  'Rationalising: multiply by the conjugate, (a − √b)(a + √b) = a² − b',
  'Partial fractions: (px + q)/((x − a)(x − b)) = A/(x − a) + B/(x − b)'],
 videos:[{ch:'TLMaths',q:'TLMaths A level maths quadratics completing the square discriminant'},
  {ch:'ExamSolutions',q:'ExamSolutions surds rationalising the denominator'},
  {ch:'Bicen Maths',q:'Bicen Maths partial fractions A level'}],
 examples:[
  {title:'Solve 3x² − 10x + 3 = 0 by factorising',
   steps:['We need two numbers that multiply to 3 × 3 = 9 and add to −10: they are −1 and −9.',
    'Split the middle term: 3x² − x − 9x + 3 = 0.',
    'Factorise in pairs: x(3x − 1) − 3(3x − 1) = 0.',
    'Take out the common bracket: (3x − 1)(x − 3) = 0.',
    'Set each factor to zero: x = 1/3 or x = 3.']},
  {title:'Find the range of f(x) = x² + 4x + 7 for all real x',
   steps:['Complete the square: x² + 4x + 7 = (x + 2)² − 4 + 7.',
    'Simplify: f(x) = (x + 2)² + 3.',
    'A square is never negative, so (x + 2)² ≥ 0 for every x.',
    'Therefore f(x) ≥ 3, with equality when x = −2.',
    'Range: f(x) ≥ 3.']}],
 questions:[
  {q:'Simplify (2x³)² × 3x⁻⁴.', a:'12x²', sol:'(2x³)² = 4x⁶; then 4x⁶ × 3x⁻⁴ = 12x².', m:2, d:1,
   hints:['Deal with the bracket first: square both the 2 and the x³.','(x³)² = x⁶ because you multiply the powers.','Now multiply: 4 × 3 and x⁶ × x⁻⁴ = x².']},
  {q:'Rationalise the denominator of 6 / (3 − √3).', a:'3 + √3', sol:'Multiply by (3 + √3)/(3 + √3): numerator 6(3 + √3), denominator 9 − 3 = 6. Result 3 + √3.', m:2, d:1,
   hints:['Multiply top and bottom by the conjugate of the denominator.','The conjugate of 3 − √3 is 3 + √3.','(3 − √3)(3 + √3) = 9 − 3 = 6, and the 6s cancel.']},
  {q:'Solve x² − 5x − 14 = 0.', a:'x = 7 or x = −2', sol:'(x − 7)(x + 2) = 0.', m:2, d:1,
   hints:['Look for two numbers that multiply to −14 and add to −5.','One is positive and one is negative, since the product is negative.','−7 and 2 work: (x − 7)(x + 2).']},
  {q:'Write x² + 6x − 1 in the form (x + p)² + q and state the coordinates of the minimum point.', a:'(x + 3)² − 10; minimum at (−3, −10)', sol:'Half of 6 is 3, so (x + 3)² = x² + 6x + 9; subtract 9 and the 1: (x + 3)² − 10. Minimum where the square is zero: x = −3, y = −10.', m:3, d:2,
   hints:['Take half the coefficient of x to find p.','(x + 3)² expands to x² + 6x + 9, so you need to adjust the constant.','The minimum happens when the bracket equals zero.']},
  {q:'Solve x² − 4x − 5 > 0.', a:'x < −1 or x > 5', sol:'Roots at x = −1 and x = 5 from (x − 5)(x + 1). The parabola opens upwards, so it is positive outside the roots.', m:3, d:2,
   hints:['Find where x² − 4x − 5 = 0 first.','Sketch the parabola — it opens upwards.','You want the parts of the curve above the x-axis.']},
  {q:'Find the value of k for which kx² + 4x + 1 = 0 has equal roots.', a:'k = 4', sol:'Equal roots means b² − 4ac = 0: 16 − 4k = 0, so k = 4.', m:2, d:2,
   hints:['"Equal roots" is a statement about the discriminant.','Set b² − 4ac equal to zero.','Here b = 4, a = k, c = 1.']},
  {q:'f(x) = 2x − 3 and g(x) = x². Find fg(x) and gf(x).', a:'fg(x) = 2x² − 3; gf(x) = (2x − 3)²', sol:'fg means apply g first: f(x²) = 2x² − 3. gf means apply f first: g(2x − 3) = (2x − 3)².', m:3, d:2,
   hints:['fg(x) means f(g(x)): do g first, then f.','For fg, substitute x² wherever f has an x.','For gf, substitute 2x − 3 wherever g has an x.']},
  {q:'Express (5x + 1) / ((x − 1)(x + 2)) in partial fractions.', a:'2/(x − 1) + 3/(x + 2)', sol:'5x + 1 = A(x + 2) + B(x − 1). x = 1: 6 = 3A, A = 2. x = −2: −9 = −3B, B = 3.', m:3, d:3,
   hints:['Write it as A/(x − 1) + B/(x + 2) and combine over the common denominator.','Equate numerators: 5x + 1 = A(x + 2) + B(x − 1).','Substitute x = 1 to kill the B term, then x = −2 to kill the A term.']}],
 exit:[{q:'Solve 2x² + x − 6 = 0.',a:'x = 3/2 or x = −2'},
  {q:'Simplify √50 − √8.',a:'3√2'},
  {q:'Describe the transformation from y = x² to y = (x − 2)² + 1.',a:'Translation by the vector (2, 1)'}]
});

ROOMS.push({
 id:'P1', name:'Proof', paper:'1/2',
 upLearn:'Proof (Pure Year 1 and Year 2 lessons)',
 pearson:'Pure Year 1: Ch 7 Algebraic methods (proof section). Pure Year 2: Ch 1 Algebraic methods (proof by contradiction)',
 concept:'Proof is small in content and generous in marks, which makes it the best-value room in pure maths. Four methods: deduction (algebra from a general starting point), exhaustion (check every case), counter-example (one case that breaks a claim), and contradiction (assume the opposite and reach an absurdity). The examiner is marking the logic, so every line must follow from the one before it, and the argument must end with a clear statement that what was asked has been shown. Vague words like "obviously" score nothing.',
 formulae:['Any even integer can be written 2k; any odd integer 2k + 1, for integer k',
  'Consecutive integers: n, n + 1, n + 2',
  'Difference of two squares: a² − b² = (a − b)(a + b)',
  'Contradiction structure: assume the negation → derive an impossibility → conclude the original statement'],
 videos:[{ch:'TLMaths',q:'TLMaths proof by contradiction root 2 irrational A level'},
  {ch:'ExamSolutions',q:'ExamSolutions proof by exhaustion counter example'}],
 examples:[
  {title:'Prove there is no largest even integer',
   steps:['Assume, for contradiction, that there is a largest even integer and call it N.',
    'Since N is even, N = 2k for some integer k.',
    'Consider N + 2 = 2k + 2 = 2(k + 1). This is also even.',
    'But N + 2 > N, contradicting the assumption that N was the largest.',
    'So the assumption is false: there is no largest even integer.']},
  {title:'Prove that (n + 2)² − n² is a multiple of 4 for any integer n',
   steps:['Expand: (n + 2)² = n² + 4n + 4.',
    'Subtract n²: (n + 2)² − n² = 4n + 4.',
    'Factorise: 4n + 4 = 4(n + 1).',
    'Since n + 1 is an integer, 4(n + 1) is a multiple of 4, as required.']}],
 questions:[
  {q:'Prove that the sum of two consecutive odd numbers is divisible by 4.', a:'(2n + 1) + (2n + 3) = 4n + 4 = 4(n + 1)', sol:'Let the numbers be 2n + 1 and 2n + 3. Their sum is 4n + 4 = 4(n + 1), a multiple of 4.', m:3, d:1,
   hints:['Write a general odd number as 2n + 1.','The next odd number is 2 more.','Add them and factorise.']},
  {q:'Disprove the statement: "n² + n + 1 is prime for all positive integers n".', a:'n = 4 gives 21 = 3 × 7, not prime', sol:'A single counter-example suffices. n = 4: 16 + 4 + 1 = 21 = 3 × 7.', m:2, d:1,
   hints:['You only need one value of n that fails.','Try small values of n in order.','n = 1, 2, 3 give 3, 7, 13 — keep going.']},
  {q:'Prove by exhaustion that no square number ends in 2, 3, 7 or 8.', a:'Last digits of squares are only 0, 1, 4, 5, 6, 9', sol:'The last digit of n² depends only on the last digit of n. Squaring 0–9 gives last digits 0, 1, 4, 9, 6, 5, 6, 9, 4, 1. None is 2, 3, 7 or 8.', m:4, d:2,
   hints:['The last digit of n² depends only on the last digit of n.','So you only have ten cases to check.','Square 0 through 9 and record each last digit.']},
  {q:'Prove that √2 is irrational.', a:'Contradiction: assume √2 = p/q in lowest terms; then p and q are both even, contradiction', sol:'Assume √2 = p/q with no common factor. Then p² = 2q², so p² is even, so p is even: p = 2m. Then 4m² = 2q², q² = 2m², so q is even too. Both even contradicts lowest terms.', m:5, d:3,
   hints:['Assume the opposite: √2 = p/q in its lowest terms.','Square both sides and show p must be even.','Substitute p = 2m and show q must be even too — that breaks "lowest terms".']},
  {q:'Prove that if n is odd, then n² is odd.', a:'(2k + 1)² = 2(2k² + 2k) + 1', sol:'n = 2k + 1, n² = 4k² + 4k + 1 = 2(2k² + 2k) + 1, which is odd.', m:3, d:1,
   hints:['Write n = 2k + 1.','Expand (2k + 1)².','Show the result has the form 2(something) + 1.']},
  {q:'Prove that for all real x and y, x² + y² ≥ 2xy.', a:'(x − y)² ≥ 0 expands to the result', sol:'(x − y)² ≥ 0 since squares are non-negative. Expanding: x² − 2xy + y² ≥ 0, so x² + y² ≥ 2xy.', m:3, d:1,
   hints:['Start from something you know is non-negative.','A square is always ≥ 0.','Expand (x − y)² and rearrange.']},
  {q:'Prove that the difference between the squares of two consecutive integers is odd.', a:'(n + 1)² − n² = 2n + 1', sol:'(n + 1)² − n² = 2n + 1, which is odd for any integer n.', m:3, d:1,
   hints:['Call the integers n and n + 1.','Expand (n + 1)² and subtract n².','Show the result has the form 2(something) + 1.']},
  {q:'Prove by contradiction that there are infinitely many prime numbers.', a:'Assume finitely many; N = product + 1 is not divisible by any of them', sol:'Assume the primes are exactly p₁, …, pₙ. Let N = p₁p₂…pₙ + 1. N leaves remainder 1 on division by each pᵢ, so no listed prime divides it. Yet N > 1 has a prime factor, which must be a new prime. Contradiction.', m:5, d:3,
   hints:['Assume there are only finitely many and list them all.','Build a new number from the product of all of them, plus 1.','Show that none of your listed primes divides this number.']}],
 exit:[{q:'Give a counter-example to "all prime numbers are odd".',a:'2'},
  {q:'Prove that the sum of three consecutive integers is a multiple of 3.',a:'n + (n + 1) + (n + 2) = 3n + 3 = 3(n + 1)'},
  {q:'Prove that n² − n is always even.',a:'n² − n = n(n − 1), the product of two consecutive integers, one of which is even'}]
});

ROOMS.push({
 id:'P3', name:'Coordinate geometry', paper:'1/2',
 upLearn:'Coordinate geometry: straight lines, circles, parametric equations',
 pearson:'Pure Year 1: Ch 5 Straight line graphs, Ch 6 Circles. Pure Year 2: Ch 8 Parametric equations',
 concept:'This room is algebra with a picture. Straight lines are gradients and intercepts; circles are a centre and a radius, usually hidden inside an expanded equation that you recover by completing the square. The two ideas meet in tangent problems, where the key fact is that a radius meets its tangent at right angles. Parametric equations arrive in Year 2 and describe a curve by a third variable; converting to Cartesian form means eliminating that variable. Sketch everything — a rough diagram catches sign errors that algebra alone will not.',
 formulae:['Gradient m = (y₂ − y₁)/(x₂ − x₁); line through (x₁, y₁): y − y₁ = m(x − x₁)',
  'Perpendicular gradients multiply to −1',
  'Distance between points: √((x₂ − x₁)² + (y₂ − y₁)²); midpoint: ((x₁ + x₂)/2, (y₁ + y₂)/2)',
  'Circle centre (a, b), radius r: (x − a)² + (y − b)² = r²',
  'Tangent to a circle is perpendicular to the radius at the point of contact',
  'Parametric → Cartesian: eliminate the parameter'],
 videos:[{ch:'TLMaths',q:'TLMaths circles completing the square tangent A level'},
  {ch:'ExamSolutions',q:'ExamSolutions parametric equations Cartesian form'}],
 examples:[
  {title:'Find where the line y = x + 1 meets the circle x² + y² = 25',
   steps:['Substitute the line into the circle: x² + (x + 1)² = 25.',
    'Expand: x² + x² + 2x + 1 = 25, so 2x² + 2x − 24 = 0.',
    'Divide by 2: x² + x − 12 = 0.',
    'Factorise: (x + 4)(x − 3) = 0, so x = −4 or x = 3.',
    'Find y from the line: points (−4, −3) and (3, 4).']},
  {title:'Perpendicular bisector of the segment joining (2, 1) and (6, 5)',
   steps:['Midpoint: ((2 + 6)/2, (1 + 5)/2) = (4, 3).',
    'Gradient of the segment: (5 − 1)/(6 − 2) = 1.',
    'Perpendicular gradient: −1.',
    'Line through (4, 3) with gradient −1: y − 3 = −(x − 4).',
    'Simplify: y = −x + 7.']}],
 questions:[
  {q:'Find the equation of the line through (1, 2) and (3, 8).', a:'y = 3x − 1', sol:'Gradient 6/2 = 3. y − 2 = 3(x − 1), so y = 3x − 1.', m:3, d:1,
   hints:['Find the gradient first.','Gradient = change in y ÷ change in x.','Then use y − y₁ = m(x − x₁) with either point.']},
  {q:'Find the line perpendicular to y = 2x + 1 that passes through (4, 1). Give your answer as ax + by + c = 0.', a:'x + 2y − 6 = 0', sol:'Perpendicular gradient −1/2. y − 1 = −½(x − 4), so 2y − 2 = −x + 4, x + 2y − 6 = 0.', m:3, d:1,
   hints:['Perpendicular gradients multiply to −1.','The new gradient is −1/2.','Clear the fraction by multiplying through by 2.']},
  {q:'Find the centre and radius of the circle x² + y² − 6x + 4y − 12 = 0.', a:'Centre (3, −2), radius 5', sol:'(x − 3)² − 9 + (y + 2)² − 4 − 12 = 0, so (x − 3)² + (y + 2)² = 25.', m:3, d:2,
   hints:['Complete the square for x and for y separately.','(x − 3)² = x² − 6x + 9 and (y + 2)² = y² + 4y + 4.','Collect the constants on the right to find r².']},
  {q:'Find the distance between (−1, 3) and (5, −5).', a:'10', sol:'√(6² + (−8)²) = √100 = 10.', m:2, d:1,
   hints:['Use Pythagoras with the differences in x and y.','The differences are 6 and −8.','√(36 + 64).']},
  {q:'Find the equation of the tangent to x² + y² = 25 at the point (3, 4).', a:'3x + 4y = 25', sol:'Radius gradient 4/3, so tangent gradient −3/4. y − 4 = −¾(x − 3): 4y − 16 = −3x + 9, so 3x + 4y = 25.', m:4, d:2,
   hints:['The tangent is perpendicular to the radius at that point.','The radius from (0, 0) to (3, 4) has gradient 4/3.','So the tangent gradient is −3/4.']},
  {q:'A(1, 1), B(4, 5), C(8, 2). Show that angle ABC is a right angle.', a:'Gradient AB = 4/3, gradient BC = −3/4, product −1', sol:'AB gradient (5 − 1)/(4 − 1) = 4/3. BC gradient (2 − 5)/(8 − 4) = −3/4. Product = −1, so AB ⟂ BC.', m:3, d:2,
   hints:['Find the gradients of AB and BC.','Perpendicular lines have gradients whose product is −1.','Make sure you use the right pairs of points for each gradient.']},
  {q:'A curve has parametric equations x = 2t, y = t². Find its Cartesian equation.', a:'y = x²/4', sol:'t = x/2, so y = (x/2)² = x²/4.', m:2, d:1,
   hints:['Make t the subject of the easier equation.','t = x/2.','Substitute into y = t².']},
  {q:'Find the equation of the circle that has the line segment from (1, 2) to (7, 10) as a diameter.', a:'(x − 4)² + (y − 6)² = 25', sol:'Centre is the midpoint (4, 6). Radius is half the diameter: √(6² + 8²)/2 = 5.', m:4, d:2,
   hints:['The centre is the midpoint of the diameter.','The radius is half the length of the diameter.','Distance from (1, 2) to (7, 10) is 10.']}],
 exit:[{q:'Find the midpoint of (2, −3) and (6, 5).',a:'(4, 1)'},
  {q:'State the centre and radius of (x + 1)² + (y − 3)² = 16.',a:'Centre (−1, 3), radius 4'},
  {q:'Find the gradient of the line 4x − 2y + 7 = 0.',a:'2'}]
});

ROOMS.push({
 id:'P4', name:'Sequences and series', paper:'1/2',
 upLearn:'Sequences and series; binomial expansion',
 pearson:'Pure Year 1: Ch 8 Binomial expansion. Pure Year 2: Ch 3 Sequences and series, Ch 4 Binomial expansion',
 concept:'Two families of sequence — arithmetic (add a constant) and geometric (multiply by a constant) — each with a formula for the nth term and for the sum of n terms, plus the special case of a geometric series that converges to a sum to infinity when |r| < 1. Sigma notation is just a compact way to write a sum. The binomial expansion starts as Pascal\'s triangle for positive integer powers and then, in Year 2, extends to fractional and negative powers where it becomes an infinite series valid only for |x| < 1. Recurrence relations describe a sequence by how to get the next term from the current one.',
 formulae:['Arithmetic: uₙ = a + (n − 1)d; Sₙ = n/2 (2a + (n − 1)d) = n/2 (a + l)',
  'Geometric: uₙ = arⁿ⁻¹; Sₙ = a(1 − rⁿ)/(1 − r); S∞ = a/(1 − r) for |r| < 1',
  'Binomial (positive integer n): (a + b)ⁿ = Σ C(n, r) aⁿ⁻ʳ bʳ',
  'Binomial (any n): (1 + x)ⁿ = 1 + nx + n(n − 1)/2! x² + n(n − 1)(n − 2)/3! x³ + …, valid for |x| < 1',
  'Σ_{r=1}^{n} r = n(n + 1)/2'],
 videos:[{ch:'TLMaths',q:'TLMaths binomial expansion negative fractional powers'},
  {ch:'ExamSolutions',q:'ExamSolutions geometric series sum to infinity'}],
 examples:[
  {title:'Expand (1 + x/2)^(1/2) up to the term in x²',
   steps:['Use (1 + y)ⁿ with n = 1/2 and y = x/2.',
    'First term: 1. Second term: n·y = (1/2)(x/2) = x/4.',
    'Third term: n(n − 1)/2 · y² = (1/2)(−1/2)/2 · (x/2)² = (−1/8)(x²/4).',
    'Simplify the third term: −x²/32.',
    'Result: 1 + x/4 − x²/32, valid for |x/2| < 1, i.e. |x| < 2.']},
  {title:'An arithmetic series has u₃ = 10 and u₇ = 22. Find S₁₀',
   steps:['u₃ = a + 2d = 10 and u₇ = a + 6d = 22.',
    'Subtract: 4d = 12, so d = 3.',
    'Then a = 10 − 6 = 4.',
    'S₁₀ = 10/2 (2·4 + 9·3) = 5(8 + 27).',
    'S₁₀ = 175.']}],
 questions:[
  {q:'An arithmetic sequence has a = 3 and d = 4. Find u₂₀ and S₂₀.', a:'u₂₀ = 79, S₂₀ = 820', sol:'u₂₀ = 3 + 19·4 = 79. S₂₀ = 20/2 (3 + 79) = 820.', m:3, d:1,
   hints:['uₙ = a + (n − 1)d.','For the sum, use n/2 (first + last).','You already have the last term from the first part.']},
  {q:'For the geometric sequence 2, 6, 18, … find u₈ and S₈.', a:'u₈ = 4374, S₈ = 6560', sol:'r = 3. u₈ = 2·3⁷ = 4374. S₈ = 2(3⁸ − 1)/(3 − 1) = 6560.', m:3, d:1,
   hints:['Find r by dividing consecutive terms.','uₙ = arⁿ⁻¹, so u₈ uses r⁷.','Sₙ = a(rⁿ − 1)/(r − 1) is easier when r > 1.']},
  {q:'Find the sum to infinity of 12 + 3 + 3/4 + …', a:'16', sol:'r = 1/4. S∞ = 12/(1 − 1/4) = 12/(3/4) = 16.', m:2, d:1,
   hints:['Find r first.','Check |r| < 1 so the sum exists.','S∞ = a/(1 − r).']},
  {q:'Expand (1 + 2x)⁵ in ascending powers of x up to and including the term in x³.', a:'1 + 10x + 40x² + 80x³', sol:'Coefficients 1, 5, 10, 10: 1 + 5(2x) + 10(2x)² + 10(2x)³ = 1 + 10x + 40x² + 80x³.', m:3, d:2,
   hints:['Use row 5 of Pascal\'s triangle: 1, 5, 10, 10, 5, 1.','Replace x with 2x everywhere.','(2x)² = 4x², (2x)³ = 8x³ — don\'t forget to raise the 2 as well.']},
  {q:'Find the coefficient of x² in the expansion of (2 + x)⁶.', a:'240', sol:'C(6, 2) · 2⁴ · x² = 15 · 16 = 240.', m:2, d:2,
   hints:['The general term is C(6, r) 2⁶⁻ʳ xʳ.','You want r = 2.','C(6, 2) = 15 and 2⁴ = 16.']},
  {q:'Expand (1 − x)⁻² in ascending powers of x up to x³, and state the range of validity.', a:'1 + 2x + 3x² + 4x³, |x| < 1', sol:'n = −2, y = −x. 1 + (−2)(−x) + (−2)(−3)/2 (−x)² + (−2)(−3)(−4)/6 (−x)³ = 1 + 2x + 3x² + 4x³.', m:4, d:3,
   hints:['Use the general binomial formula with n = −2.','Substitute y = −x carefully, keeping the signs.','Every term comes out positive — a good check.']},
  {q:'Find Σ_{r=1}^{n} (3r + 1) in terms of n.', a:'(3n² + 5n)/2', sol:'3 Σr + Σ1 = 3n(n + 1)/2 + n = (3n² + 3n + 2n)/2 = (3n² + 5n)/2.', m:3, d:2,
   hints:['Split the sum: 3Σr + Σ1.','Σ_{r=1}^{n} r = n(n + 1)/2 and Σ_{r=1}^{n} 1 = n.','Put over a common denominator of 2.']},
  {q:'A sequence is defined by u₁ = 5, uₙ₊₁ = 2uₙ − 3. Find u₂, u₃ and u₄.', a:'7, 11, 19', sol:'u₂ = 10 − 3 = 7; u₃ = 14 − 3 = 11; u₄ = 22 − 3 = 19.', m:2, d:1,
   hints:['Each term is found from the one before it.','u₂ = 2(5) − 3.','Keep going, one term at a time.']}],
 exit:[{q:'Find the 5th term of an arithmetic sequence with a = 7 and d = −2.',a:'−1'},
  {q:'Find the common ratio of 81, 27, 9, …',a:'1/3'},
  {q:'Evaluate C(8, 3).',a:'56'}]
});

ROOMS.push({
 id:'P5', name:'Trigonometry', paper:'1/2',
 upLearn:'Trigonometry: ratios, identities, radians, compound angles',
 pearson:'Pure Year 1: Ch 9 Trigonometric ratios, Ch 10 Trigonometric identities and equations. Pure Year 2: Ch 5 Radians, Ch 6 Trigonometric functions, Ch 7 Trigonometry and modelling',
 concept:'Trigonometry is the room that decays fastest without practice, so it gets the most frequent reviews. Year 1: exact values, the sine and cosine rules, the graphs and how to read all solutions of an equation from them, and the two identities that everything else is built on. Year 2: radians (arcs, sectors, small-angle approximations), the reciprocal and inverse functions, and the compound and double-angle formulae — including writing a sin x + b cos x as a single R sin(x + α), which turns a messy expression into one you can read the maximum straight off. Draw the graph or the CAST diagram every time you solve an equation; the marks are in finding all the solutions, not the first one.',
 formulae:['sin²x + cos²x = 1; 1 + tan²x = sec²x; 1 + cot²x = cosec²x',
  'Arc length s = rθ; sector area A = ½r²θ (θ in radians)',
  'sin(A ± B) = sin A cos B ± cos A sin B; cos(A ± B) = cos A cos B ∓ sin A sin B',
  'sin 2A = 2 sin A cos A; cos 2A = cos²A − sin²A = 2cos²A − 1 = 1 − 2sin²A',
  'a sin x + b cos x = R sin(x + α) with R = √(a² + b²), tan α = b/a',
  'Small angles: sin θ ≈ θ, cos θ ≈ 1 − θ²/2, tan θ ≈ θ'],
 videos:[{ch:'TLMaths',q:'TLMaths R sin(x + alpha) harmonic form A level'},
  {ch:'ExamSolutions',q:'ExamSolutions solving trig equations CAST diagram all solutions'},
  {ch:'Bicen Maths',q:'Bicen Maths small angle approximations'}],
 examples:[
  {title:'Solve sin(2x + 30°) = 0.5 for 0° ≤ x < 180°',
   steps:['Let u = 2x + 30°. As x runs from 0° to 180°, u runs from 30° to 390°.',
    'Solve sin u = 0.5 in that range: u = 30°, 150° (390° is not included).',
    'Back-substitute: 2x + 30 = 30 gives x = 0°; 2x + 30 = 150 gives x = 60°.',
    'Check both are in 0° ≤ x < 180°: they are.',
    'Solutions: x = 0°, 60°.']},
  {title:'Prove that cos 2x = 1 − 2sin²x',
   steps:['Start from cos(A + B) = cos A cos B − sin A sin B with A = B = x.',
    'So cos 2x = cos²x − sin²x.',
    'Use cos²x = 1 − sin²x.',
    'cos 2x = (1 − sin²x) − sin²x = 1 − 2sin²x, as required.']}],
 questions:[
  {q:'Convert 150° to radians, and find the arc length of a sector with radius 6 and angle π/3.', a:'5π/6; arc length 2π', sol:'150° × π/180 = 5π/6. s = rθ = 6 × π/3 = 2π.', m:3, d:1,
   hints:['180° = π radians.','150/180 simplifies to 5/6.','Arc length is rθ with θ in radians.']},
  {q:'Find the area of a sector with radius 5 and angle 1.2 radians.', a:'15', sol:'A = ½ × 25 × 1.2 = 15.', m:2, d:1,
   hints:['Use A = ½r²θ.','r² = 25.','Half of 25 × 1.2.']},
  {q:'Solve sin x = 1/2 for 0° ≤ x < 360°.', a:'30°, 150°', sol:'Principal value 30°; sine is also positive in the second quadrant: 180° − 30° = 150°.', m:2, d:1,
   hints:['Find the principal value first.','Sine is positive in two quadrants.','The second solution is 180° minus the first.']},
  {q:'Solve 2cos²x − cos x = 0 for 0 ≤ x ≤ 2π.', a:'π/2, 3π/2, π/3, 5π/3', sol:'cos x (2cos x − 1) = 0. cos x = 0: x = π/2, 3π/2. cos x = 1/2: x = π/3, 5π/3.', m:4, d:2,
   hints:['Factorise — do not divide by cos x, you would lose solutions.','cos x (2cos x − 1) = 0.','Solve each factor separately over the whole range.']},
  {q:'Prove that tan x + cot x ≡ sec x cosec x.', a:'(sin²x + cos²x)/(sin x cos x) = 1/(sin x cos x)', sol:'tan x + cot x = sin x/cos x + cos x/sin x = (sin²x + cos²x)/(sin x cos x) = 1/(sin x cos x) = sec x cosec x.', m:3, d:2,
   hints:['Write everything in terms of sin and cos.','Combine over a common denominator sin x cos x.','Use sin²x + cos²x = 1 in the numerator.']},
  {q:'Express 3 sin x + 4 cos x in the form R sin(x + α), R > 0, 0 < α < 90°. Hence state the maximum value and the smallest positive x at which it occurs.', a:'5 sin(x + 53.1°); max 5 at x = 36.9°', sol:'R = 5, tan α = 4/3 so α = 53.13°. Maximum 5 when x + 53.13 = 90, x = 36.87°.', m:5, d:2,
   hints:['R = √(3² + 4²).','Expand R sin(x + α) and compare coefficients: R cos α = 3, R sin α = 4.','The maximum of sin is 1, when the argument is 90°.']},
  {q:'Show that for small θ, (1 − cos 2θ)/(θ sin θ) ≈ 2.', a:'(2θ²)/(θ²) = 2', sol:'cos 2θ ≈ 1 − (2θ)²/2 = 1 − 2θ², so 1 − cos 2θ ≈ 2θ². sin θ ≈ θ. Ratio ≈ 2θ²/θ² = 2.', m:3, d:3,
   hints:['Use cos θ ≈ 1 − θ²/2 with θ replaced by 2θ.','1 − cos 2θ ≈ 2θ².','sin θ ≈ θ in the denominator.']},
  {q:'A and B are acute angles with sin A = 3/5 and cos B = 5/13. Find the exact value of sin(A + B).', a:'63/65', sol:'cos A = 4/5, sin B = 12/13. sin(A + B) = (3/5)(5/13) + (4/5)(12/13) = 15/65 + 48/65 = 63/65.', m:4, d:2,
   hints:['You need cos A and sin B: use right-angled triangles or sin² + cos² = 1.','cos A = 4/5 and sin B = 12/13.','Apply sin(A + B) = sin A cos B + cos A sin B.']}],
 exit:[{q:'State the exact value of cos(π/6).',a:'√3/2'},
  {q:'State the identity linking sin²x and cos²x.',a:'sin²x + cos²x = 1'},
  {q:'Solve tan x = 1 for 0° ≤ x < 180°.',a:'45°'}]
});

module.exports = { ROOMS };
