/* Content — Statistics and Mechanics rooms, technique dojo, boundaries, weights. */
const ROOMS = [];

ROOMS.push({
 id:'S1', name:'Statistical sampling', paper:'3',
 upLearn:'Statistical sampling and the large data set',
 pearson:'Statistics & Mechanics Year 1: Ch 1 Data collection',
 concept:'A small room with reliably cheap marks. You need the vocabulary — population, census, sample, sampling frame, sampling unit — and the five sampling methods with one advantage and one disadvantage each: simple random, systematic, stratified, quota and opportunity. Questions are mostly short-answer and mark the precision of your wording, so learn the definitions exactly. The large data set lives here too: Edexcel expects you to know its structure and quirks well enough to spot a nonsensical value or a coded entry. Download the current data set from Pearson early and spend an hour with it; it cannot be crammed in May.',
 formulae:['Stratified sample size for a stratum = (stratum size / population size) × total sample size',
  'Systematic: interval k = population size / sample size; random start between 1 and k',
  'Simple random: every possible sample of that size is equally likely',
  'Quota: strata filled by interviewer judgement (non-random); Opportunity: whoever is available'],
 videos:[{ch:'TLMaths',q:'TLMaths sampling methods stratified systematic quota'},
  {ch:'ExamSolutions',q:'ExamSolutions Edexcel large data set A level statistics'}],
 examples:[
  {title:'Stratified sample: 300 boys and 200 girls, a sample of 40 is needed',
   steps:['Population is 500. Sample fraction is 40/500 = 0.08.',
    'Boys: 300 × 0.08 = 24.',
    'Girls: 200 × 0.08 = 16.',
    'Check: 24 + 16 = 40. Within each stratum, select by simple random sampling.']},
  {title:'Systematic sample of 20 from a list of 1000',
   steps:['Interval k = 1000/20 = 50.',
    'Choose a random start between 1 and 50, say 17.',
    'Select items 17, 67, 117, …, 967.',
    'Weakness: if the list has a repeating pattern every 50, the sample is biased.']}],
 questions:[
  {q:'Define simple random sampling and state one advantage and one disadvantage.', a:'Every sample of size n equally likely; unbiased but needs a sampling frame', sol:'Every possible sample of size n has an equal chance. Advantage: free from bias, easy to analyse. Disadvantage: needs a full sampling frame; may be impractical for large populations.', m:3, d:1,
   hints:['The definition is about every sample being equally likely.','Think about what you need before you can start.','Bias is the advantage; practicality is the disadvantage.']},
  {q:'Describe how to take a systematic sample of 20 from a list of 1000 employees.', a:'k = 50; random start 1–50; every 50th', sol:'Number the list 1–1000. k = 1000/20 = 50. Choose a random start between 1 and 50, then take every 50th name.', m:3, d:1,
   hints:['Find the interval first.','The starting point must be chosen at random.','Then step through the list at fixed intervals.']},
  {q:'A school has 300 boys and 200 girls. A stratified sample of 40 is taken. How many of each?', a:'24 boys, 16 girls', sol:'40/500 = 0.08. 300 × 0.08 = 24, 200 × 0.08 = 16.', m:2, d:1,
   hints:['Find the fraction of the population being sampled.','Apply that fraction to each stratum.','Check the totals add to 40.']},
  {q:'State the key difference between quota sampling and opportunity sampling.', a:'Quota fills preset strata by judgement; opportunity takes anyone available with no strata', sol:'Quota sampling divides the population into groups and fills a set number from each by interviewer choice. Opportunity sampling has no such structure — the sample is whoever is available. Neither is random.', m:2, d:2,
   hints:['Both are non-random.','One of them uses strata.','What guides who gets picked in each?']},
  {q:'Give one advantage of a census over a sample.', a:'Completely accurate — every member is included', sol:'It gives a completely accurate result because every member of the population is included. (Disadvantage: expensive and time-consuming, and may destroy items tested.)', m:1, d:1,
   hints:['A census asks everyone.','So what can a sample never guarantee?','Accuracy.']},
  {q:'In the large data set, some rainfall values are recorded as "tr". What does this mean and how should it be treated in calculations?', a:'Trace — less than 0.05 mm; treat as 0', sol:'"tr" means a trace of rainfall, too small to measure. It is treated as 0 in calculations.', m:2, d:2,
   hints:['It is a coded value, not missing data.','It stands for a very small amount.','Numerically it is treated as zero.']},
  {q:'Explain why a systematic sample may be biased if the list has a repeating pattern.', a:'Fixed interval may align with the pattern so the same type of item is always chosen', sol:'If the pattern repeats with a period matching the sampling interval, every selected item has the same characteristic, so some groups are never sampled.', m:2, d:2,
   hints:['The interval is fixed.','What if the list alternates in some way?','Could you keep landing on the same kind of item?']},
  {q:'Explain the difference between a population and a sampling frame.', a:'Population is everyone of interest; sampling frame is the actual list used to select from', sol:'The population is the whole group being studied. The sampling frame is the list of members from which the sample is drawn — it may not include everyone in the population.', m:2, d:1,
   hints:['One is the concept, one is the concrete list.','Can a list ever be incomplete?','That gap is the difference.']}],
 exit:[{q:'A population has 500 in group A and 300 in group B. Find a stratified sample of 80.',a:'50 from A, 30 from B'},
  {q:'What is a census?',a:'A survey of every member of the population'},
  {q:'Give one disadvantage of opportunity sampling.',a:'Likely to be biased / unrepresentative'}]
});

ROOMS.push({
 id:'S2', name:'Data presentation', paper:'3',
 upLearn:'Measures of location and spread; representations of data; correlation and regression',
 pearson:'Statistics & Mechanics Year 1: Ch 2 Measures of location and spread, Ch 3 Representations of data, Ch 4 Correlation. Year 2: Ch 1 Regression, correlation and hypothesis testing',
 concept:'Summarising data: measures of location (mean, median, mode) and spread (range, IQR, variance, standard deviation), including from grouped data by interpolation and from coded data. Representing it: histograms (where area, not height, is frequency), box plots and the outlier rule, cumulative frequency, and scatter diagrams with correlation and regression. The exam rewards interpretation in context as much as calculation — "strong negative correlation between temperature and heating cost" scores where "r = −0.85" alone does not. Your calculator does the arithmetic; your job is to set it up correctly and say what the number means.',
 formulae:['Mean x̄ = Σx/n = Σfx/Σf',
  'Variance σ² = Σx²/n − x̄² = (Sₓₓ)/n; standard deviation σ = √variance',
  'Coding y = (x − a)/b: ȳ = (x̄ − a)/b, σᵧ = σₓ/b',
  'Outlier (common rule): below Q₁ − 1.5 × IQR or above Q₃ + 1.5 × IQR',
  'Frequency density = frequency / class width',
  'Regression line y = a + bx: b is the change in y per unit change in x; only interpolate within the data range'],
 videos:[{ch:'TLMaths',q:'TLMaths variance standard deviation coding A level statistics'},
  {ch:'ExamSolutions',q:'ExamSolutions histograms frequency density interpolation'},
  {ch:'Bicen Maths',q:'Bicen Maths regression correlation interpretation Edexcel'}],
 examples:[
  {title:'Find the mean and standard deviation from Σx = 120, Σx² = 1500, n = 10',
   steps:['Mean x̄ = 120/10 = 12.',
    'Σx²/n = 1500/10 = 150.',
    'Variance = 150 − 12² = 150 − 144 = 6.',
    'Standard deviation = √6 = 2.45 (3 s.f.).']},
  {title:'Estimate the median of grouped data by interpolation',
   steps:['Suppose n = 40, so the median is the 20th value, and it lies in the class 20 ≤ x < 30 which starts at cumulative frequency 14 and has frequency 12.',
    'The median is (20 − 14)/12 = 6/12 = 0.5 of the way through the class.',
    'Class width is 10, so add 0.5 × 10 = 5 to the lower boundary.',
    'Median ≈ 20 + 5 = 25.']}],
 questions:[
  {q:'Find the mean and standard deviation of 2, 4, 4, 4, 5, 5, 7, 9.', a:'Mean 5, sd 2', sol:'Σx = 40, mean 5. Σx² = 232, Σx²/n = 29, variance = 29 − 25 = 4, sd = 2.', m:3, d:1,
   hints:['Add them up and divide by 8.','Variance = Σx²/n − mean².','Σx² = 4 + 16 + 16 + 16 + 25 + 25 + 49 + 81.']},
  {q:'Find the median and interquartile range of 3, 7, 8, 12, 15, 18, 21.', a:'Median 12, IQR 11', sol:'Median is the 4th value, 12. Q₁ = 7 (2nd), Q₃ = 18 (6th). IQR = 11.', m:3, d:1,
   hints:['With 7 values, the median is the 4th.','Q₁ is the median of the lower half, Q₃ of the upper half.','IQR = Q₃ − Q₁.']},
  {q:'For the data in the previous question, calculate the outlier boundaries using the 1.5 × IQR rule.', a:'−9.5 and 34.5', sol:'Q₁ − 1.5 × 11 = 7 − 16.5 = −9.5. Q₃ + 16.5 = 34.5. No outliers.', m:2, d:2,
   hints:['1.5 × IQR = 16.5.','Subtract from Q₁ and add to Q₃.','Then check whether any data lie outside.']},
  {q:'A histogram has a class 10 ≤ x < 15 with frequency 30. Find the frequency density.', a:'6', sol:'Frequency density = 30/5 = 6.', m:1, d:1,
   hints:['Frequency density = frequency ÷ class width.','Class width is 15 − 10 = 5.','30 ÷ 5.']},
  {q:'Data are coded using y = (x − 100)/5. The coded data have mean 4 and standard deviation 2. Find the mean and standard deviation of x.', a:'Mean 120, sd 10', sol:'x̄ = 5ȳ + 100 = 120. σₓ = 5σᵧ = 10.', m:3, d:2,
   hints:['Reverse the coding for the mean: x = 5y + 100.','Adding 100 shifts the mean but not the spread.','Multiplying by 5 scales the standard deviation.']},
  {q:'Interpret a product moment correlation coefficient of r = −0.85 between the temperature and the daily heating cost of a building.', a:'Strong negative correlation: as temperature rises, heating cost tends to fall', sol:'Strong negative linear correlation. In context: higher temperatures are associated with lower heating costs.', m:2, d:1,
   hints:['Strength: how close to ±1?','Direction: what does the sign tell you?','Always finish with what it means for the variables named.']},
  {q:'A regression line for y (crop yield in tonnes) on x (rainfall in cm) is y = 3.2 + 0.8x, based on data with 20 ≤ x ≤ 60. Interpret the gradient, and explain why it is unwise to use the line to predict yield when x = 100.', a:'Each extra cm of rain is associated with 0.8 t more yield; x = 100 is extrapolation outside the data', sol:'Gradient: yield increases by 0.8 tonnes per extra centimetre of rainfall. x = 100 is far outside the range of the data, so the linear relationship may not hold — extrapolation is unreliable.', m:3, d:2,
   hints:['The gradient is a rate: units of y per unit of x.','Say it in context.','Compare 100 with the data range.']},
  {q:'A cumulative frequency graph is drawn for 80 observations. Explain how to estimate the median and the interquartile range from it.', a:'Read x at cumulative frequencies 40, 20 and 60', sol:'Median: read across from cumulative frequency 40 to the curve and down to x. Q₁ from 20, Q₃ from 60; IQR = Q₃ − Q₁.', m:3, d:2,
   hints:['The median is the middle observation — the 40th.','Quartiles are at a quarter and three quarters.','Read from the vertical axis to the curve to the horizontal axis.']}],
 exit:[{q:'Find the mean of 4, 8, 9, 11.',a:'8'},
  {q:'Which five values does a box plot show?',a:'Minimum, Q₁, median, Q₃, maximum'},
  {q:'In a histogram, what represents frequency?',a:'Area of the bar'}]
});

ROOMS.push({
 id:'S3', name:'Probability', paper:'3',
 upLearn:'Probability: Venn diagrams, tree diagrams, conditional probability',
 pearson:'Statistics & Mechanics Year 1: Ch 5 Probability. Year 2: Ch 2 Conditional probability',
 concept:'Probability is about counting carefully and knowing which rule applies. Mutually exclusive events cannot both happen (add the probabilities); independent events do not affect each other (multiply them). Venn diagrams organise overlapping events; tree diagrams organise sequences, especially without replacement. Year 2 adds conditional probability and the formula that links it to the intersection, and the test for independence that follows from it. Set notation — ∩, ∪, the prime for complement — is examinable in its own right. Draw the diagram first; the algebra falls out of the picture.',
 formulae:['P(A ∪ B) = P(A) + P(B) − P(A ∩ B)',
  'Mutually exclusive: P(A ∩ B) = 0, so P(A ∪ B) = P(A) + P(B)',
  'Independent: P(A ∩ B) = P(A) P(B); equivalently P(A | B) = P(A)',
  'Conditional: P(A | B) = P(A ∩ B) / P(B)',
  'Complement: P(A′) = 1 − P(A)',
  'Tree diagrams: multiply along branches, add between branches'],
 videos:[{ch:'TLMaths',q:'TLMaths conditional probability Venn diagram A level'},
  {ch:'ExamSolutions',q:'ExamSolutions tree diagrams without replacement'}],
 examples:[
  {title:'From a Venn diagram: P(A) = 0.6, P(B) = 0.5, P(A ∪ B) = 0.8. Find P(A ∩ B) and P(A | B). Are A and B independent?',
   steps:['P(A ∩ B) = P(A) + P(B) − P(A ∪ B) = 0.6 + 0.5 − 0.8 = 0.3.',
    'P(A | B) = P(A ∩ B)/P(B) = 0.3/0.5 = 0.6.',
    'P(A | B) = 0.6 = P(A).',
    'Since P(A | B) = P(A), the events A and B are independent.']},
  {title:'A bag has 3 red and 5 blue counters. Two are taken without replacement. Find P(at least one red)',
   steps:['P(both blue) = 5/8 × 4/7 = 20/56 = 5/14.',
    '"At least one red" is the complement of "both blue".',
    'P(at least one red) = 1 − 5/14 = 9/14.',
    'Check by direct route: RR + RB + BR = 6/56 + 15/56 + 15/56 = 36/56 = 9/14. ✓']}],
 questions:[
  {q:'A and B are independent with P(A) = 0.4 and P(B) = 0.5. Find P(A ∩ B) and P(A ∪ B).', a:'0.2 and 0.7', sol:'P(A ∩ B) = 0.4 × 0.5 = 0.2. P(A ∪ B) = 0.4 + 0.5 − 0.2 = 0.7.', m:3, d:1,
   hints:['Independent means multiply for the intersection.','Then use the addition rule for the union.','Don\'t double-count the overlap.']},
  {q:'A and B are mutually exclusive with P(A) = 0.3 and P(B) = 0.45. Find P(A ∪ B).', a:'0.75', sol:'Mutually exclusive means P(A ∩ B) = 0, so P(A ∪ B) = 0.3 + 0.45.', m:1, d:1,
   hints:['Mutually exclusive: no overlap.','So just add.','0.3 + 0.45.']},
  {q:'Two fair dice are rolled. Find the probability that the total is 7.', a:'1/6', sol:'Six outcomes total 7 out of 36: (1,6), (2,5), (3,4), (4,3), (5,2), (6,1).', m:2, d:1,
   hints:['There are 36 equally likely outcomes.','List the pairs that add to 7.','There are six of them.']},
  {q:'A bag contains 3 red and 5 blue counters. Two are drawn without replacement. Find P(both red).', a:'3/28', sol:'3/8 × 2/7 = 6/56 = 3/28.', m:2, d:2,
   hints:['Draw a tree diagram.','After one red is taken, 2 red remain out of 7.','Multiply along the branch.']},
  {q:'P(A ∩ B) = 0.12 and P(B) = 0.3. Find P(A | B).', a:'0.4', sol:'0.12/0.3 = 0.4.', m:1, d:1,
   hints:['Use the conditional probability formula.','P(A | B) = P(A ∩ B)/P(B).','Divide.']},
  {q:'P(A) = 0.6, P(B) = 0.5, P(A ∪ B) = 0.8. Find P(A ∩ B) and determine whether A and B are independent.', a:'P(A ∩ B) = 0.3; independent, since 0.6 × 0.5 = 0.3', sol:'P(A ∩ B) = 0.6 + 0.5 − 0.8 = 0.3. P(A)P(B) = 0.3 = P(A ∩ B), so independent.', m:3, d:2,
   hints:['Rearrange the addition rule to find the intersection.','Independence test: does P(A)P(B) equal P(A ∩ B)?','0.6 × 0.5 = 0.3.']},
  {q:'P(B) = 0.5 and P(A ∩ B) = 0.2. Find P(A′ ∩ B).', a:'0.3', sol:'P(A′ ∩ B) = P(B) − P(A ∩ B) = 0.5 − 0.2 = 0.3.', m:2, d:1,
   hints:['Draw a Venn diagram and shade the part of B outside A.','That region is B minus the overlap.','0.5 − 0.2.']},
  {q:'Three fair coins are tossed. Find the probability of at least one head.', a:'7/8', sol:'P(no heads) = (1/2)³ = 1/8. P(at least one head) = 1 − 1/8 = 7/8.', m:2, d:1,
   hints:['"At least one" — think about the complement.','P(all tails) = 1/8.','Subtract from 1.']}],
 exit:[{q:'P(A) = 0.35. Find P(A′).',a:'0.65'},
  {q:'A and B are independent with P(A) = 0.2, P(B) = 0.6. Find P(A ∩ B).',a:'0.12'},
  {q:'On a tree diagram, what do you do with probabilities along a single path?',a:'Multiply them'}]
});

ROOMS.push({
 id:'S4', name:'Statistical distributions', paper:'3',
 upLearn:'Discrete distributions, the binomial and the normal distribution',
 pearson:'Statistics & Mechanics Year 1: Ch 6 Statistical distributions. Year 2: Ch 3 The normal distribution',
 concept:'A distribution is a complete description of how likely each outcome is. Discrete random variables come first — probabilities that sum to 1 — then the binomial, which models the number of successes in a fixed number of independent trials with constant probability. Year 2 brings the normal distribution: the bell curve, standardising to Z, using the calculator to find probabilities and inverse probabilities, finding unknown μ or σ from given probabilities, and approximating a binomial with a normal when n is large and p near ½. Half the marks in this room are for stating the conditions under which a model is appropriate; know them cold.',
 formulae:['Discrete RV: Σ P(X = x) = 1',
  'Binomial X ~ B(n, p): P(X = r) = C(n, r) pʳ (1 − p)ⁿ⁻ʳ; mean np; variance np(1 − p)',
  'Binomial conditions: fixed n, two outcomes, constant p, independent trials',
  'Normal X ~ N(μ, σ²): Z = (X − μ)/σ ~ N(0, 1)',
  'About 68% within 1σ, 95% within 2σ, 99.7% within 3σ',
  'Normal approximation to B(n, p) when n large, p ≈ 0.5: N(np, np(1 − p)), with continuity correction'],
 videos:[{ch:'TLMaths',q:'TLMaths normal distribution finding mu and sigma A level'},
  {ch:'ExamSolutions',q:'ExamSolutions binomial distribution Casio calculator'},
  {ch:'Bicen Maths',q:'Bicen Maths normal approximation binomial continuity correction'}],
 examples:[
  {title:'X ~ N(30, 4²). Find a such that P(X < a) = 0.975',
   steps:['P(Z < z) = 0.975 gives z = 1.96 (inverse normal).',
    'Standardise: (a − 30)/4 = 1.96.',
    'a − 30 = 7.84.',
    'a = 37.84.']},
  {title:'X ~ B(12, 0.3). Find P(X ≥ 5)',
   steps:['"At least 5" is the complement of "at most 4".',
    'P(X ≥ 5) = 1 − P(X ≤ 4).',
    'From the calculator (binomial CD): P(X ≤ 4) = 0.7237.',
    'P(X ≥ 5) = 1 − 0.7237 = 0.2763.']}],
 questions:[
  {q:'X ~ B(10, 0.3). Find P(X = 3).', a:'0.267', sol:'C(10, 3) × 0.3³ × 0.7⁷ = 120 × 0.027 × 0.08235 = 0.2668.', m:2, d:1,
   hints:['Use the binomial formula or binomial PD on the calculator.','C(10, 3) = 120.','0.3³ × 0.7⁷.']},
  {q:'X ~ B(20, 0.4). Find P(X ≤ 6).', a:'0.250', sol:'Binomial CD with n = 20, p = 0.4, x = 6 gives 0.2500.', m:1, d:1,
   hints:['This is a cumulative probability.','Use binomial CD (or the tables).','Read off at x = 6.']},
  {q:'Z ~ N(0, 1). Find P(Z < 1.5).', a:'0.9332', sol:'Standard normal CD gives 0.9332.', m:1, d:1,
   hints:['Use the normal CD function.','Lower limit −∞ (or −99), upper 1.5.','μ = 0, σ = 1.']},
  {q:'X ~ N(50, 4²). Find P(X > 56).', a:'0.0668', sol:'Z = (56 − 50)/4 = 1.5. P(Z > 1.5) = 1 − 0.9332 = 0.0668.', m:2, d:2,
   hints:['Standardise: how many standard deviations above the mean is 56?','Z = 1.5.','You want the upper tail.']},
  {q:'X ~ N(μ, 5²) and P(X < 70) = 0.9. Find μ to 3 significant figures.', a:'μ = 63.6', sol:'z = 1.2816. (70 − μ)/5 = 1.2816, so μ = 70 − 6.408 = 63.6.', m:3, d:3,
   hints:['Find the z-value with P(Z < z) = 0.9 using inverse normal.','z = 1.2816.','Set (70 − μ)/5 equal to it and solve.']},
  {q:'A discrete random variable has P(X = x) = kx for x = 1, 2, 3, 4. Find k.', a:'k = 1/10', sol:'k(1 + 2 + 3 + 4) = 10k = 1, so k = 1/10.', m:2, d:1,
   hints:['Probabilities must sum to 1.','k + 2k + 3k + 4k.','10k = 1.']},
  {q:'X ~ B(100, 0.4). State a suitable normal approximation, giving its mean and variance.', a:'N(40, 24)', sol:'np = 40, np(1 − p) = 100 × 0.4 × 0.6 = 24. n is large and p is close to 0.5, so N(40, 24) is appropriate.', m:2, d:2,
   hints:['Mean of a binomial is np.','Variance is np(1 − p).','State why the approximation is valid.']},
  {q:'State the four conditions for a binomial distribution to be a suitable model.', a:'Fixed number of trials; two outcomes; constant probability; independent trials', sol:'Fixed n; each trial has exactly two outcomes; probability of success constant; trials independent.', m:2, d:1,
   hints:['How many trials?','How many outcomes per trial?','What must stay the same, and what must not affect what?']}],
 exit:[{q:'Find P(Z > 0) for Z ~ N(0, 1).',a:'0.5'},
  {q:'Find the mean of X ~ B(50, 0.2).',a:'10'},
  {q:'Which distribution models "the number of heads in 10 tosses of a fair coin"?',a:'B(10, 0.5)'}]
});

ROOMS.push({
 id:'S5', name:'Hypothesis testing', paper:'3',
 upLearn:'Hypothesis testing: binomial, correlation, normal mean',
 pearson:'Statistics & Mechanics Year 1: Ch 7 Hypothesis testing. Year 2: Ch 1 Regression, correlation and hypothesis testing; Ch 3 The normal distribution (testing a mean)',
 concept:'A hypothesis test asks whether the data are surprising enough, under an assumption, to make you doubt that assumption. Every test has the same skeleton: state H₀ and H₁ in terms of a parameter, choose the significance level, find the probability of a result at least as extreme (or the critical region), compare, and conclude in context without overclaiming. Year 1 tests a binomial probability; Year 2 tests a correlation coefficient and the mean of a normal population. The conclusion sentence is worth a mark on every test and is the one students most often fumble: "there is insufficient evidence to reject H₀" is right; "H₀ is true" is wrong.',
 formulae:['Binomial test: under H₀, X ~ B(n, p₀); p-value = P(X ≥ x) or P(X ≤ x)',
  'Critical region: set of values of the test statistic that lead to rejecting H₀',
  'Actual significance level = probability of the critical region under H₀',
  'Correlation test: compare r with the critical value for n at the given level',
  'Mean of a normal sample: X̄ ~ N(μ, σ²/n); z = (x̄ − μ₀)/(σ/√n)',
  'Two-tailed: split α between the two tails'],
 videos:[{ch:'TLMaths',q:'TLMaths hypothesis testing binomial critical region A level'},
  {ch:'ExamSolutions',q:'ExamSolutions hypothesis test for the mean of a normal distribution'},
  {ch:'Bicen Maths',q:'Bicen Maths hypothesis test correlation coefficient Edexcel'}],
 examples:[
  {title:'Full write-up: a coin is claimed fair; in 20 tosses it lands heads 15 times. Test at 5% whether it is biased towards heads',
   steps:['H₀: p = 0.5, H₁: p > 0.5, where p is the probability of a head. Significance level 5%.',
    'Under H₀, X ~ B(20, 0.5). Test statistic: X = 15.',
    'P(X ≥ 15) = 1 − P(X ≤ 14) = 1 − 0.9793 = 0.0207.',
    '0.0207 < 0.05, so the result is significant. Reject H₀.',
    'Conclusion in context: there is evidence, at the 5% level, that the coin is biased towards heads.']},
  {title:'Critical region: X ~ B(15, 0.3) under H₀, H₁: p < 0.3, at 5%',
   steps:['We want the largest c such that P(X ≤ c) ≤ 0.05.',
    'P(X ≤ 1) = 0.0353; P(X ≤ 2) = 0.1268.',
    'So the critical region is X ≤ 1.',
    'Actual significance level = 0.0353 = 3.53%.']}],
 questions:[
  {q:'H₀: p = 0.3, H₁: p > 0.3. In 20 trials, 10 successes are observed. Test at the 5% level.', a:'P(X ≥ 10) = 0.048 < 0.05; reject H₀', sol:'Under H₀, X ~ B(20, 0.3). P(X ≥ 10) = 1 − P(X ≤ 9) = 1 − 0.9520 = 0.0480 < 0.05. Reject H₀: evidence that p > 0.3.', m:4, d:2,
   hints:['State the distribution under H₀.','You want the probability of 10 or more — a complement.','Compare with 0.05 and conclude in words.']},
  {q:'X ~ B(15, 0.5) under H₀, with H₁: p ≠ 0.5. Find the critical region at the 5% level and the actual significance level.', a:'X ≤ 3 or X ≥ 12; actual level 3.52%', sol:'Two-tailed, 2.5% each tail. P(X ≤ 3) = 0.0176 ≤ 0.025; P(X ≤ 4) = 0.0592 too big. By symmetry upper tail X ≥ 12. Actual level = 2 × 0.0176 = 0.0352.', m:5, d:3,
   hints:['Two tails, so 2.5% in each.','Find the largest lower value with cumulative probability ≤ 0.025.','The distribution is symmetric, so mirror for the upper tail.']},
  {q:'Explain what is meant by the significance level of a test.', a:'The probability of rejecting H₀ when it is true', sol:'The probability of rejecting H₀ when H₀ is actually true — the threshold below which a result is considered too unlikely to be chance.', m:1, d:1,
   hints:['It is a probability.','It concerns making a particular mistake.','Rejecting a true H₀.']},
  {q:'A sample of 10 pairs gives r = 0.65. Test at 5% whether there is positive correlation. (Critical value for n = 10, one-tailed 5%: 0.5494.)', a:'0.65 > 0.5494; reject H₀: evidence of positive correlation', sol:'H₀: ρ = 0, H₁: ρ > 0. 0.65 > 0.5494, so reject H₀. Evidence at the 5% level of positive correlation.', m:3, d:2,
   hints:['State H₀ and H₁ in terms of ρ.','Compare r with the critical value.','Conclude in context.']},
  {q:'X ~ N(μ, 3²). A sample of 16 has mean 52. Test H₀: μ = 50 against H₁: μ ≠ 50 at the 5% level.', a:'z = 2.67 > 1.96; reject H₀', sol:'X̄ ~ N(50, 9/16) under H₀, so σ/√n = 0.75. z = (52 − 50)/0.75 = 2.667. Two-tailed critical value 1.96. Reject H₀: evidence the mean is not 50.', m:4, d:3,
   hints:['The sample mean has standard deviation σ/√n.','σ/√n = 3/4.','Two-tailed at 5% uses ±1.96.']},
  {q:'Explain the difference between the significance level and the actual significance level of a binomial test.', a:'Nominal level is the chosen threshold; actual level is the true probability of the critical region', sol:'The significance level is the chosen value, e.g. 5%. Because the binomial is discrete, the critical region rarely has probability exactly 5%; the actual significance level is its true probability, usually a little less.', m:2, d:1,
   hints:['One is chosen; one is calculated.','Why can\'t they always match for a binomial?','Discrete distributions jump.']},
  {q:'A test at 5% gives a p-value of 0.031. Write the conclusion in context for a test of whether a new fertiliser increases yield.', a:'Reject H₀: there is evidence at the 5% level that the fertiliser increases yield', sol:'0.031 < 0.05, so reject H₀. There is evidence, at the 5% level, that the new fertiliser increases yield. (Not: "the fertiliser increases yield".)', m:2, d:1,
   hints:['Compare p with 0.05.','"Reject" or "insufficient evidence to reject".','Say what that means for the fertiliser, without overclaiming.']},
  {q:'A researcher believes a die is biased but does not know in which direction. Should the test be one-tailed or two-tailed? Explain.', a:'Two-tailed: H₁ specifies no direction', sol:'Two-tailed, because H₁ is p ≠ 1/6 — bias in either direction would support the claim.', m:1, d:1,
   hints:['Does the claim specify a direction?','"Biased" alone could mean higher or lower.','No direction means two tails.']}],
 exit:[{q:'Write H₀ and H₁ for testing whether a coin is biased towards heads.',a:'H₀: p = 0.5, H₁: p > 0.5'},
  {q:'What is a critical region?',a:'The set of test statistic values for which H₀ is rejected'},
  {q:'Give the test statistic for a normal mean test.',a:'z = (x̄ − μ₀)/(σ/√n)'}]
});

ROOMS.push({
 id:'M6', name:'Quantities and units', paper:'3',
 upLearn:'Modelling in mechanics: quantities, units and assumptions',
 pearson:'Statistics & Mechanics Year 1: Ch 8 Modelling in mechanics',
 concept:'The shortest room in the course and the one that unlocks the rest of mechanics. You need the SI units and their derivations, the difference between scalars and vectors, and the vocabulary of modelling: particle, light, inextensible, smooth, rough, uniform, rigid. Each word is a promise about what can be ignored. Exam questions ask you to state an assumption and say what effect removing it would have, and those marks are as cheap as any in Paper 3 if the definitions are known exactly.',
 formulae:['Force: newton, N = kg m s⁻²; weight W = mg with g = 9.8 m s⁻²',
  'Velocity m s⁻¹, acceleration m s⁻², moment N m',
  'Scalars: distance, speed, mass, time. Vectors: displacement, velocity, acceleration, force',
  'Particle: dimensions ignored. Light: mass ignored. Inextensible: constant length. Smooth: no friction. Uniform: mass evenly spread'],
 videos:[{ch:'TLMaths',q:'TLMaths modelling assumptions mechanics A level'},
  {ch:'ExamSolutions',q:'ExamSolutions scalars vectors units mechanics'}],
 examples:[
  {title:'Identify the modelling assumptions: "A book rests on a smooth horizontal table and is pulled by a light inextensible string"',
   steps:['Smooth table: no friction acts between book and table.',
    'Light string: the string has no mass, so tension is the same throughout it.',
    'Inextensible string: the string does not stretch, so the book moves with the same acceleration as whatever pulls the string.',
    'Implicitly, the book is a particle: its size and rotation are ignored.']},
  {title:'Convert 72 km h⁻¹ to m s⁻¹',
   steps:['72 km = 72 000 m.',
    '1 hour = 3600 s.',
    '72 000/3600 = 20.',
    'So 72 km h⁻¹ = 20 m s⁻¹.']}],
 questions:[
  {q:'State the SI units of force and of moment, and express the newton in base units.', a:'N and N m; 1 N = 1 kg m s⁻²', sol:'Force in newtons, moment in newton metres. From F = ma, N = kg × m s⁻².', m:2, d:1,
   hints:['Force comes from F = ma.','Multiply the units of mass and acceleration.','A moment is force × distance.']},
  {q:'Classify as scalar or vector: speed, velocity, distance, displacement.', a:'Speed scalar, velocity vector, distance scalar, displacement vector', sol:'Vectors have direction; scalars do not.', m:2, d:1,
   hints:['Does the quantity have a direction?','Speed is "how fast"; velocity is "how fast and which way".','Same pattern for distance and displacement.']},
  {q:'A ball is modelled as a particle. What does this mean, and why is it reasonable?', a:'Its dimensions are ignored; it is small compared with the distances involved and rotation is neglected', sol:'All its mass is treated as at a single point. Reasonable when its size is small relative to the motion and air resistance and spin are ignored.', m:2, d:2,
   hints:['A particle has no size.','What does that let you ignore?','When is that a fair thing to ignore?']},
  {q:'Convert 72 km h⁻¹ to m s⁻¹.', a:'20 m s⁻¹', sol:'72 000 m per 3600 s = 20.', m:2, d:1,
   hints:['Convert kilometres to metres.','Convert hours to seconds.','Divide.']},
  {q:'Find the weight of a 5 kg mass, taking g = 9.8 m s⁻².', a:'49 N', sol:'W = mg = 5 × 9.8.', m:1, d:1,
   hints:['Weight is a force.','W = mg.','5 × 9.8.']},
  {q:'A string is described as "inextensible". State what this means and one consequence for the motion of two particles it connects.', a:'It does not stretch; the two particles have the same acceleration', sol:'Its length is constant. Consequently connected particles move with the same speed and acceleration along the string.', m:2, d:2,
   hints:['Inextensible is about length.','If the length cannot change, how do the ends move?','Same acceleration.']},
  {q:'State the difference between a "rough" and a "smooth" surface in a mechanics model.', a:'Rough: friction acts; smooth: no friction', sol:'A smooth surface exerts only a normal reaction; a rough surface also exerts friction.', m:1, d:1,
   hints:['It is about one specific force.','Friction.','Which surface has it?']},
  {q:'A particle has position vector (3i + 4j) m. Find its distance from the origin.', a:'5 m', sol:'√(9 + 16) = 5.', m:1, d:1,
   hints:['Distance is the magnitude of the position vector.','Use Pythagoras on the components.','√(9 + 16) = √25.']}],
 exit:[{q:'State the SI unit of acceleration.',a:'m s⁻²'},
  {q:'Is mass a scalar or a vector?',a:'Scalar'},
  {q:'What does "light" mean when describing a string?',a:'Its mass can be ignored'}]
});

ROOMS.push({
 id:'M7', name:'Kinematics', paper:'3',
 upLearn:'Kinematics: constant and variable acceleration, projectiles',
 pearson:'Statistics & Mechanics Year 1: Ch 9 Constant acceleration, Ch 11 Variable acceleration. Year 2: Ch 6 Projectiles, Ch 8 Further kinematics',
 concept:'Kinematics describes motion without asking what causes it. Year 1: motion graphs (gradient of a displacement graph is velocity, area under a velocity graph is displacement), the five suvat equations for constant acceleration, and vertical motion under gravity. Where acceleration varies, calculus takes over — differentiate to go from displacement to velocity to acceleration, integrate to go back. Year 2 adds projectiles (treat horizontal and vertical motion separately, linked only by time) and motion in two dimensions with vectors. Choose a positive direction and write it down before the first line of working. Sign errors are the whole story in this room.',
 formulae:['suvat: v = u + at; s = ut + ½at²; s = ½(u + v)t; v² = u² + 2as; s = vt − ½at²',
  'v = ds/dt, a = dv/dt; s = ∫ v dt, v = ∫ a dt',
  'Projectile: horizontal x = (u cos θ)t; vertical y = (u sin θ)t − ½gt²',
  'Time of flight (level ground) = 2u sin θ / g; range = u² sin 2θ / g',
  'Vector form: r = r₀ + ut + ½at²'],
 videos:[{ch:'TLMaths',q:'TLMaths projectiles A level mechanics'},
  {ch:'ExamSolutions',q:'ExamSolutions suvat equations vertical motion under gravity'},
  {ch:'Bicen Maths',q:'Bicen Maths variable acceleration calculus mechanics'}],
 examples:[
  {title:'A ball is projected at 20 m s⁻¹ at 30° above the horizontal from level ground. Find the time of flight and the range',
   steps:['Vertical: u sin 30 = 10. Taking upwards positive, y = 10t − 4.9t².',
    'Lands when y = 0: t(10 − 4.9t) = 0, so t = 10/4.9 = 2.04 s.',
    'Horizontal: velocity u cos 30 = 17.32 m s⁻¹, constant.',
    'Range = 17.32 × 2.04 = 35.3 m.',
    'Check with the formula: u² sin 60/g = 400 × 0.866/9.8 = 35.3. ✓']},
  {title:'A particle moves with v = 3t² − 4t. Find its acceleration and its displacement from t = 0 to t = 2',
   steps:['a = dv/dt = 6t − 4.',
    'Displacement = ∫₀² (3t² − 4t) dt = [t³ − 2t²]₀².',
    'At t = 2: 8 − 8 = 0. At t = 0: 0.',
    'Displacement is 0: the particle returns to where it started, though the distance travelled is not zero.']}],
 questions:[
  {q:'A car accelerates from rest at 2 m s⁻² for 5 s. Find its final velocity and the distance travelled.', a:'v = 10 m s⁻¹, s = 25 m', sol:'v = 0 + 2 × 5 = 10. s = 0 + ½ × 2 × 25 = 25.', m:3, d:1,
   hints:['List u, a, t; you want v and s.','v = u + at.','s = ut + ½at².']},
  {q:'A car travelling at 20 m s⁻¹ decelerates at 4 m s⁻² to rest. Find the stopping distance.', a:'50 m', sol:'v² = u² + 2as: 0 = 400 − 8s, s = 50.', m:2, d:1,
   hints:['You have u, v, a; you want s with no t.','v² = u² + 2as.','Deceleration means a = −4.']},
  {q:'A velocity–time graph rises from 0 to 10 m s⁻¹ in 4 s, stays at 10 for 6 s, then falls to 0 in 2 s. Find the total displacement.', a:'90 m', sol:'Areas: ½ × 4 × 10 = 20; 6 × 10 = 60; ½ × 2 × 10 = 10. Total 90.', m:3, d:2,
   hints:['Displacement is the area under the velocity–time graph.','Split into a triangle, a rectangle and a triangle.','Add the three areas.']},
  {q:'A ball is thrown vertically upwards at 14.7 m s⁻¹. Find the maximum height reached and the time taken to reach it.', a:'11.0 m; 1.5 s', sol:'At the top v = 0. v² = u² + 2as: 0 = 216.09 − 19.6s, s = 11.03. v = u + at: 0 = 14.7 − 9.8t, t = 1.5.', m:4, d:2,
   hints:['At maximum height the velocity is zero.','Take upwards positive, so a = −9.8.','Use v² = u² + 2as for height and v = u + at for time.']},
  {q:'A projectile is launched at 20 m s⁻¹ at 30° above horizontal ground. Find its horizontal range.', a:'35.3 m', sol:'Time of flight 2 × 10/9.8 = 2.041 s. Range = 20 cos 30 × 2.041 = 35.3 m.', m:4, d:3,
   hints:['Split into horizontal and vertical components.','Find the time of flight from the vertical motion.','Range = horizontal speed × time of flight.']},
  {q:'A particle moves so that v = 3t² − 4t. Find its acceleration when t = 3, and its displacement between t = 0 and t = 2.', a:'a = 14 m s⁻²; displacement 0', sol:'a = 6t − 4 = 14. ∫₀² (3t² − 4t) dt = [t³ − 2t²]₀² = 0.', m:4, d:2,
   hints:['Differentiate for acceleration.','Integrate for displacement.','Zero displacement does not mean zero distance.']},
  {q:'A particle has position vector r = 2t² i + (3t − t²) j metres at time t seconds. Find its velocity when t = 1.', a:'4i + j m s⁻¹', sol:'v = dr/dt = 4t i + (3 − 2t) j. At t = 1: 4i + j.', m:3, d:2,
   hints:['Differentiate each component with respect to t.','d/dt (2t²) = 4t; d/dt (3t − t²) = 3 − 2t.','Substitute t = 1.']},
  {q:'Train A passes a point at a constant 30 m s⁻¹. At the same instant train B starts from rest at that point with acceleration 2 m s⁻². When and where does B catch A?', a:'After 30 s, 900 m from the point', sol:'A: s = 30t. B: s = t². Equal when t² = 30t, t = 30 (t = 0 is the start). s = 900 m.', m:4, d:3,
   hints:['Write an expression for each train\'s displacement in terms of t.','Set them equal.','Reject the trivial solution t = 0.']}],
 exit:[{q:'u = 5, a = 2, t = 3. Find s.',a:'24'},
  {q:'What does the gradient of a velocity–time graph represent?',a:'Acceleration'},
  {q:'u = 3, a = −2, t = 4. Find v.',a:'−5'}]
});

ROOMS.push({
 id:'M8', name:'Forces and Newton\u2019s laws', paper:'3',
 upLearn:'Forces and motion, friction, connected particles, inclined planes',
 pearson:'Statistics & Mechanics Year 1: Ch 10 Forces and motion. Year 2: Ch 5 Forces and friction, Ch 7 Applications of forces',
 concept:'The biggest mechanics room and the one with the most marks. Newton\'s second law, F = ma, applied along a chosen direction, with the forces resolved into components: weight, normal reaction, tension, thrust, friction, driving force. Year 1: horizontal motion and connected particles over smooth pulleys. Year 2: friction (F ≤ μR, with equality when the object slides or is about to), inclined planes (resolve along and perpendicular to the slope), and equilibrium problems. The method that scores every time: draw the diagram with every force labelled, state the positive direction, write F = ma for each body separately. A diagram earns a B mark on its own.',
 formulae:['Newton II: resultant force = ma (along the direction of motion)',
  'Newton III: forces between two bodies are equal and opposite',
  'Friction: F ≤ μR; F = μR when moving or in limiting equilibrium',
  'On a slope of angle α: weight components mg sin α (down the slope) and mg cos α (into the slope)',
  'Connected particles: same acceleration magnitude; tension the same throughout a light string over a smooth pulley',
  'Equilibrium: resultant force zero in every direction'],
 videos:[{ch:'TLMaths',q:'TLMaths connected particles pulley A level mechanics'},
  {ch:'ExamSolutions',q:'ExamSolutions friction inclined plane resolving forces'},
  {ch:'Bicen Maths',q:'Bicen Maths forces mechanics Edexcel A level'}],
 examples:[
  {title:'Masses of 3 kg and 5 kg hang from a light inextensible string over a smooth pulley. Find the acceleration and the tension',
   steps:['Diagram: 5 kg accelerates down, 3 kg accelerates up; tension T in both parts; weights 5g and 3g.',
    'For the 5 kg (down positive): 5g − T = 5a.',
    'For the 3 kg (up positive): T − 3g = 3a.',
    'Add: 2g = 8a, so a = g/4 = 2.45 m s⁻².',
    'Substitute: T = 3(g + a) = 3(9.8 + 2.45) = 36.75 N.']},
  {title:'A 2 kg block slides down a rough plane inclined at 30°, μ = 0.2. Find its acceleration',
   steps:['Perpendicular to the slope: R = 2g cos 30 = 16.97 N.',
    'Friction acts up the slope (opposing motion): F = μR = 0.2 × 16.97 = 3.39 N.',
    'Along the slope, down positive: 2g sin 30 − F = 2a.',
    '9.8 − 3.39 = 2a.',
    'a = 3.20 m s⁻².']}],
 questions:[
  {q:'A resultant force of 10 N acts on a 4 kg mass. Find its acceleration.', a:'2.5 m s⁻²', sol:'a = F/m = 10/4.', m:1, d:1,
   hints:['F = ma.','Rearrange for a.','10 ÷ 4.']},
  {q:'Forces (3i + 2j) N and (−i + 4j) N act on a particle. Find the magnitude of the resultant.', a:'2√10 N (≈ 6.32 N)', sol:'Resultant 2i + 6j. Magnitude √(4 + 36) = √40 = 2√10.', m:2, d:1,
   hints:['Add the vectors component by component.','Then find the magnitude with Pythagoras.','√40 simplifies.']},
  {q:'A 2 kg mass hangs from a string and accelerates upwards at 2 m s⁻². Find the tension.', a:'23.6 N', sol:'T − 2g = 2 × 2, so T = 19.6 + 4 = 23.6.', m:2, d:2,
   hints:['Two forces: tension up, weight down.','Take upwards as positive: T − mg = ma.','mg = 19.6.']},
  {q:'A 3 kg block is released on a smooth plane inclined at 30°. Find its acceleration.', a:'4.9 m s⁻²', sol:'Along the slope: 3g sin 30 = 3a, a = 9.8 × 0.5 = 4.9.', m:2, d:2,
   hints:['Resolve weight along the slope.','Smooth means no friction.','The mass cancels.']},
  {q:'A 4 kg block on a rough horizontal surface (μ = 0.5) is pulled by a horizontal force of 25 N. Find its acceleration.', a:'1.35 m s⁻²', sol:'R = 4g = 39.2. F = μR = 19.6. 25 − 19.6 = 4a, a = 1.35.', m:3, d:2,
   hints:['Find the normal reaction first — vertically nothing moves.','Friction = μR opposes the pull.','Net horizontal force = 4a.']},
  {q:'Particles of 3 kg and 5 kg are connected by a light inextensible string over a smooth fixed pulley and released from rest. Find the acceleration and the tension.', a:'a = 2.45 m s⁻², T = 36.75 N', sol:'5g − T = 5a and T − 3g = 3a. Adding: 2g = 8a, a = 2.45. T = 3(9.8 + 2.45) = 36.75.', m:5, d:3,
   hints:['Write F = ma for each particle separately.','The tension is the same in both parts; the accelerations have equal magnitude.','Add the two equations to eliminate T.']},
  {q:'A 2 kg block slides down a rough plane inclined at 30° to the horizontal, μ = 0.2. Find its acceleration.', a:'3.20 m s⁻²', sol:'R = 2g cos 30 = 16.97. F = 0.2R = 3.39. 2g sin 30 − 3.39 = 2a, a = 3.20.', m:5, d:3,
   hints:['Resolve perpendicular to the slope to find R.','Friction = μR acts up the slope.','Resolve along the slope: mg sin α − F = ma.']},
  {q:'State Newton\'s third law and give an example involving a book resting on a table.', a:'Forces between two bodies are equal and opposite; the table pushes up on the book with the same force the book pushes down on the table', sol:'If body A exerts a force on body B, then B exerts an equal and opposite force on A. The book presses down on the table; the table exerts an equal upward normal reaction on the book.', m:2, d:1,
   hints:['It is about a pair of forces between two bodies.','Equal in magnitude, opposite in direction.','Name both forces in the book–table example.']}],
 exit:[{q:'Find the weight of a 10 kg mass (g = 9.8).',a:'98 N'},
  {q:'m = 2 kg, a = 3 m s⁻². Find the resultant force.',a:'6 N'},
  {q:'What is the normal reaction?',a:'The contact force perpendicular to the surface'}]
});

ROOMS.push({
 id:'M9', name:'Moments', paper:'3',
 upLearn:'Moments and equilibrium of rigid bodies',
 pearson:'Statistics & Mechanics Year 2: Ch 4 Moments',
 concept:'A moment is the turning effect of a force: force times perpendicular distance from the pivot. Rigid bodies in equilibrium satisfy two conditions at once — the resultant force is zero, and the total moment about any point is zero. The art is choosing the point to take moments about: pick the one that makes the unknown you don\'t want disappear. Uniform rods have their weight at the midpoint; non-uniform rods hide the centre of mass and ask you to find it. Tilting problems ask when a reaction becomes zero. Every question in this room starts with a diagram showing each force and each distance.',
 formulae:['Moment = force × perpendicular distance from the pivot, in N m; state clockwise or anticlockwise',
  'Equilibrium: sum of forces = 0 and sum of moments about any point = 0',
  'Uniform rod: weight acts at the midpoint',
  'On the point of tilting about a support: the reaction at the other support is zero'],
 videos:[{ch:'TLMaths',q:'TLMaths moments non uniform rod tilting A level'},
  {ch:'ExamSolutions',q:'ExamSolutions moments equilibrium rigid bodies'}],
 examples:[
  {title:'A uniform beam AB of length 6 m and weight 300 N rests on supports at A and at C, 4 m from A. A child of weight 200 N stands at D, 5 m from A. Find the reactions',
   steps:['Diagram: R_A up at A, R_C up at C (4 m), weight 300 N at the midpoint (3 m), child 200 N at 5 m.',
    'Moments about A (kills R_A): R_C × 4 = 300 × 3 + 200 × 5 = 900 + 1000 = 1900.',
    'R_C = 475 N.',
    'Vertical forces: R_A + R_C = 500, so R_A = 25 N.',
    'Check by moments about C: R_A × 4 = 300 × 1 − 200 × 1 → 100/4 = 25. ✓']},
  {title:'A non-uniform rod of length 5 m and weight 100 N hangs horizontally from two vertical strings at its ends with tensions 60 N and 40 N. Find the position of the centre of mass',
   steps:['Let the centre of mass be x m from the 60 N end.',
    'Take moments about the 60 N end: 100 × x = 40 × 5.',
    '100x = 200.',
    'x = 2 m from the 60 N end (closer to the end with the larger tension, as expected).']}],
 questions:[
  {q:'A force of 10 N acts at a perpendicular distance of 3 m from a pivot. Find the moment.', a:'30 N m', sol:'10 × 3.', m:1, d:1,
   hints:['Moment = force × perpendicular distance.','10 × 3.','Include the units.']},
  {q:'A uniform rod AB of length 4 m and weight 40 N is pivoted at a point 1 m from A. Find the vertical force that must be applied at A to keep it horizontal.', a:'40 N', sol:'Weight acts 2 m from A, i.e. 1 m from the pivot on the B side. Moments about the pivot: F × 1 = 40 × 1, F = 40 N.', m:3, d:2,
   hints:['The weight acts at the midpoint of a uniform rod.','Measure distances from the pivot.','Balance clockwise and anticlockwise moments.']},
  {q:'A uniform beam of length 6 m and weight 300 N rests on supports at its ends. Find the reaction at each support.', a:'150 N each', sol:'By symmetry, each support carries half the weight.', m:2, d:1,
   hints:['The beam is uniform and the supports are symmetric.','Total upward force equals the weight.','Split equally.']},
  {q:'A uniform beam AB, length 6 m, weight 300 N, rests on supports at A and C where AC = 4 m. A child of weight 200 N stands at D, 5 m from A. Find the reactions at A and C.', a:'R_C = 475 N, R_A = 25 N', sol:'Moments about A: 4R_C = 900 + 1000, R_C = 475. Vertically R_A = 500 − 475 = 25.', m:5, d:3,
   hints:['Take moments about A to eliminate R_A.','Weight acts at 3 m, child at 5 m.','Then use vertical equilibrium for R_A.']},
  {q:'A non-uniform rod of length 5 m and weight 100 N is held horizontal by vertical strings at each end with tensions 60 N and 40 N. Find the distance of the centre of mass from the 60 N end.', a:'2 m', sol:'Moments about the 60 N end: 100x = 40 × 5, x = 2.', m:3, d:2,
   hints:['Let the centre of mass be x from one end.','Take moments about that end.','Only the weight and the far tension have moments.']},
  {q:'Explain why it matters whether a moment is clockwise or anticlockwise.', a:'Moments in opposite senses have opposite signs; equilibrium requires clockwise total = anticlockwise total', sol:'Moments have a sense of rotation. For equilibrium, the total clockwise moment must equal the total anticlockwise moment about any point, so the sense determines the sign.', m:1, d:1,
   hints:['A moment is a turning effect.','Turning effects can cancel.','What must balance for no rotation?']},
  {q:'State the two conditions for a rigid body to be in equilibrium.', a:'Resultant force zero; resultant moment about any point zero', sol:'The vector sum of the forces is zero, and the sum of the moments about any point is zero.', m:2, d:1,
   hints:['One condition is about forces.','One is about moments.','"About any point" is part of the statement.']},
  {q:'A uniform rod AB of length 4 m and weight 80 N rests horizontally on supports at C and D, where AC = 1 m and AD = 3 m. A load W is hung from A. Find the value of W for which the rod is on the point of tilting.', a:'W = 80 N', sol:'On the point of tilting about C, the reaction at D is zero. Moments about C: W × 1 = 80 × 1, W = 80 N.', m:4, d:3,
   hints:['Which support does it tilt about? The one nearer the load.','On the point of tilting, the other reaction is zero.','Take moments about the tilting support.']}],
 exit:[{q:'State the units of a moment.',a:'N m'},
  {q:'Where does the weight of a uniform rod act?',a:'At its midpoint'},
  {q:'On the point of tilting about a support, what is the reaction at the other support?',a:'Zero'}]
});

/* ---------------- Technique dojo: spot the lost mark ---------------- */
const DOJO = [
 {q:'Find the coordinates of the stationary points of y = x³ − 6x² + 5.', m:4,
  lines:['(0, 5) and (4, −27)'], lost:[0],
  why:'Both answers are correct and the score is 0/4. No derivative is shown, so neither M mark is earned, and the A marks depend on them. Write dy/dx, set it to zero, solve, then find y.'},
 {q:'Show that (n + 2)² − n² = 4(n + 1).', m:2,
  lines:['(n + 2)² − n² = 4(n + 1)', 'as required'], lost:[0,1],
  why:'In a "show that", the given result earns nothing. The marks are for the expansion (n² + 4n + 4 − n²) and the simplification (4n + 4). Restating the answer is not showing it.'},
 {q:'Find the exact area of a triangle with sides 6 cm and 8 cm and included angle 60°.', m:2,
  lines:['Area = ½ × 6 × 8 × sin 60°', '= 20.78 cm²'], lost:[1],
  why:'The method line is right and earns the M mark. "Exact" means the answer must be 12√3, not 20.78. A decimal loses the A mark even though it is numerically correct.'},
 {q:'A coin is tossed 20 times and lands heads 15 times. Test at the 5% level whether it is biased towards heads.', m:4,
  lines:['H₀: p = 0.5, H₁: p > 0.5', 'X ~ B(20, 0.5), P(X ≥ 15) = 0.0207', '0.0207 < 0.05', 'The coin is biased.'], lost:[3],
  why:'Everything up to the comparison is perfect. The conclusion overclaims: a test gives evidence, not proof. "There is evidence at the 5% level that the coin is biased towards heads" earns the mark; "the coin is biased" does not.'},
 {q:'A 2 kg mass hangs from a string and accelerates upwards at 3 m s⁻². Find the tension.', m:3,
  lines:['2g − T = 2 × 3', 'T = 19.6 − 6', 'T = 13.6 N'], lost:[0,1,2],
  why:'No diagram, and the positive direction was never chosen, so the equation is the wrong way round: the mass accelerates upwards, so T − 2g = 2a and T = 25.6 N. The B mark for a labelled diagram was also available and not taken.'},
 {q:'Evaluate ∫₁³ (2x + 1) dx.', m:3,
  lines:['= x² + x + c', '= 9 + 3 + c', '= 12 + c'], lost:[0,1,2],
  why:'The integration is correct but this is a definite integral: no + c, and the lower limit must be subtracted. [x² + x]₁³ = (9 + 3) − (1 + 1) = 10. Two A marks lost to one habit.'},
 {q:'(a) Factorise x² − 5x + 6. (b) Hence solve x² − 5x + 6 = 0.', m:3,
  lines:['(a) (x − 2)(x − 3)', '(b) x = (5 ± √(25 − 24))/2', 'x = 2 or x = 3'], lost:[1],
  why:'Part (a) is fine. "Hence" means use part (a): set each factor to zero. The quadratic formula gets the right answer by the wrong route and can score zero for part (b).'}
];

/* ---------------- Read the question ---------------- */
const READ = [
 {word:'Show that', means:'The answer is given. Every mark is in the working. Write every intermediate line, and finish by stating the result.'},
 {word:'Hence', means:'You must use the previous part. A correct answer by another method can score zero.'},
 {word:'Hence or otherwise', means:'You may use the previous part or any valid method. "Hence" is usually quicker.'},
 {word:'Exact value', means:'Surds, π, e, ln, fractions — never a rounded decimal. 20.78 loses the mark; 12√3 earns it.'},
 {word:'State', means:'A single answer with no working required. Do not waste time justifying it.'},
 {word:'Find', means:'Working is expected. Method marks are available and you should show them.'},
 {word:'Verify', means:'Substitute the given value and show the equation holds. You are not solving it from scratch.'},
 {word:'Interpret', means:'Say what the number means in the context of the question, in a sentence. The calculation alone is not the answer.'}
];

/* ---------------- Grade boundaries (Pearson, raw marks) ---------------- */
const BOUNDARIES = {
 overall:[
  {series:'June 2025', 'A*':258, A:214, B:177, C:141, D:106, E:71},
  {series:'June 2024', 'A*':251, A:205, B:167, C:130, D:93, E:56}],
 paper:{
  P1:{'A*':88, A:74, B:61, C:48, D:36, E:24},
  P2:{'A*':83, A:67, B:55, C:44, D:33, E:22},
  P3:{'A*':87, A:73, B:61, C:49, D:37, E:25}},
 note:'June 2025 overall A*/A are published values; B–E for 2025 are the summed notional component boundaries. Per-paper values are the June 2025 notional component boundaries.'
};

/* Approximate marks available per topic out of 300, for grade prediction */
const WEIGHTS = {
 P1:15, P2:30, P3:15, P4:15, P5:25, P6:15, P7:30, P8:30, P9:10, P10:15,
 S1:5, S2:12, S3:10, S4:12, S5:11,
 M6:4, M7:16, M8:20, M9:10
};

module.exports = { ROOMS, DOJO, READ, BOUNDARIES, WEIGHTS };
